### ISSUE TITLE
Add `migrate to Bitnami` section to README.md

### ISSUE THREAD

**Issue by altendky** [bitnami/bitnami-docker-phabricator#102]
I just did a temporary recovery of a Phabricator backup to get a Phriction page from it.  While I strongly appreciate the inclusion in the docs of instructions for migrating _away_ from this container I think it would also be useful to provide instructions for migrating into one.

Below is a tidied version of what I did to import my backup.  It got me to the point of logging in and seeing the Phriction page I needed.  It does not cover repositories or file stores.  It may do other bad things...  but it may be a useful start at documenting the steps to migrate into this container.

---

* On Host

  ```bash
  docker cp backup.sql /bitnami/backup/sql
  docker exec -i -t the_phabricator_container /bin/bash
  ```

* In Container

  ```bash
  nami stop phabricator
  /opt/bitnami/phabricator/bin/storage destroy
  /opt/bitnami/phabricator/bin/storage renamespace --from $(grep -m 1 '^CREATE DATABASE' /bitnami/backup.sql | sed 's/.*`\([^`]\+\)_[^_]\+`.*/\1/') --to bitnami_phabricator > /bitnami/renamespaced.sql
  mysql --host mariadb < /bitnami/renamespaced.sql
  rm /bitnami/backup.sql /bitnami/renamespaced.sql
  /opt/bitnami/phabricator/bin/storage upgrade
  /opt/bitnami/phabricator/bin/config set phabricator.base-uri http://$PHABRICATOR_HOST
  exit
   ```

* On Host

  ```bash
  docker restart the_phabricator_container
  ```

**Comment by altendky** [comment]
Hmm, it looks like you actually have several of these commands already under the 'migrate from' section, though not the renamespace.  Anyways, it might still be worth separating the section out a little bit.

**Comment by tompizmor** [comment]
Right now we have [this section](https://github.com/bitnami/bitnami-docker-phabricator#how-to-migrate-from-a-bitnami-phabricator-stack) that explains how to migrate from a Bitnami Phabricator stack to a Bitnami Phabricator container.

I agree that it would be nice to also have the opposite. However, as this is a nice-to-have and not a critical feature, there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

In any case, thanks for filling the issue and also for sharing the instructions that you followed as it can help other users.

**Comment by altendky** [comment]
@stale, I don't believe this has been resolved.

**Comment by juan131** [comment]
Hello @altendky 

I just want to let you know that we just released a new major version including several improvements that break backwards compatibility. Please read carefully the Notable Section below:

- https://github.com/bitnami/bitnami-docker-phabricator/blob/master/README.md#notable-changes

I just want to highlight that using this new image as it is (using the default non-root user) will complicate even more the migration process from a Bitnami Phabricator container to a Bitnami Phabricator VM. I'd try to make a PR explaining the process in the following days.

**Comment by altendky** [comment]
@juan131 thanks for the heads up.

**Comment by juan131** [comment]
Hi @altendky 

I just wanted to let you know that Phabricator README.md was updated including the guide you requested, please give it a try when you have a chance.
