### ISSUE TITLE
svn binary is not available in the PATH

### ISSUE THREAD

**Issue by The-Judge** [bitnami/bitnami-docker-phabricator#107]
**Description**

`svn` binary is not available in the PATH.

**Steps to reproduce the issue:**

1. Create a new "Observed" SVN repository in Diffusion.
2. Notice that will fail as soon as that Repo is activated, since the command is unsuccessful.

**Describe the results you received:**

```
Error updating working copy: Command failed with error #127!
COMMAND
svn --non-interactive --no-auth-cache --trust-server-cert --username '********' --password '********' info --xml 'https://...'

STDOUT
(empty)

STDERR
sh: 1: svn: not found
```

**Version**

- Output of `docker version`:

```
fra_revprox_out04 $ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
- Image hash: 055fdc8c19ea

- Output of `docker info`:

```
fra_revprox_out04 $ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Linux Mint 18.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.49GiB
Name: mrichter
ID: 6RHL:UMUN:BOYV:G4WJ:7NHS:DENA:IVAU:O4MF:7Q7R:EZ2B:ZEK7:IKZK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
fra_revprox_out04 $ docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by The-Judge** [comment]
Hi @tompizmor ,
thanks for that. I know how to change that, but I think that should be included by default, since it is needed to cover functionality of the containerized application and thus might be considered a soft-requirement. Git is also available.

**Comment by tompizmor** [comment]
Thanks for the feedback! I understand your concerns. 

I think it makes sense to add it by default so you can use it directly without installing any software. However, we also have to take into account the container size and the amount of user interested in the functionality. 

We will evaluate it and update this issue once we have taken a decision.

**Comment by beltran-rubo** [comment]
We think that would make the container bigger for all the users and others would also request to add other CLI tools like Hg or Bazaar. I would strongly recommend to customize your container image and add the CLI tools you use.

**Comment by HoffmannP** [comment]
Maybe install required binaries in the initial setup? Or document how to solve that issue when showing the error. I'm not sure.

**Comment by sameersbn** [comment]
@HoffmannP as suggested by @tompizmor you can extend this image and install additional packages.

1. Step 1

Create a `Dockerfile` like so:

```dockerfile
FROM bitnami/phabricator:2019.47.0-debian-9-r8
RUN install_packages subversion subversion-tools
```

Please note  `install_packages` is a helper script present in the bitnami base distribution. You could use `apt-get` as well if you choose to do so. 

2. Build the image

```bash
$ docker build -t $USER/phabricator:2019.47.0-debian-9-r8 .
```

You new docker image will have the required tools
