### ISSUE TITLE
What is the default administrator account?

### ISSUE THREAD

**Issue by heqingbao** [bitnami/bitnami-docker-phabricator#109]
What is the default username and password after the installation is complete?

![image](https://user-images.githubusercontent.com/2290475/49875101-215ca980-fe5b-11e8-8976-dbc291b76d5c.png)

**Comment by juan131** [comment]
As you can check in the Configuration section of the **README.md**, if you didn't change the credentials via env. variables, the credentials are:

- Username: `user`
- Password: `bitnami1`

More info: https://github.com/bitnami/bitnami-docker-phabricator#environment-variables

**Comment by heqingbao** [comment]
> As you can check in the Configuration section of the **README.md**, if you didn't change the credentials via env. variables, the credentials are:
> 
> * Username: `user`
> * Password: `bitnami1`
> 
> More info: https://github.com/bitnami/bitnami-docker-phabricator#environment-variables

Sorry, I didn't see it carefully before. No problem now, thank you for your reply.

**Comment by bingalls** [comment]
I installed phabricator on Azure, but could not log in with user / bitnami1 nor user@example.com / bitnami1 . Readme is not readily available in that environment.

**Comment by juan131** [comment]
Please note that this README.md refers to the container image @bingalls 

Are you using a container or a single VM in Azure? When running a single VM please refers to the docs below:

https://docs.bitnami.com/azure/apps/phabricator/get-started/first-steps/
