### ISSUE TITLE
Error while setting up phabricator with existing database

### ISSUE THREAD

**Issue by ethicalmohit** [bitnami/bitnami-docker-phabricator#117]
**Description**

We already have a phabricator setup with preexisting database. We are trying to use the existing database which is not available as of now.

We may change the code accordingly to use an existing database, which has phabricator already installed but it is trying to create a new database which we don't want it to do. 

is there any possible workaround for this situation?

**Error:**

```
Mar 10 15:59:58 ip-10-0-239-149.ec2.internal phabricator: phabric INFO  Creating Database...
Mar 10 15:59:58 ip-10-0-239-149.ec2.internal phabricator: Error executing 'postInstallation': MySQL command failed to run. Error: 
Mar 10 15:59:58 ip-10-0-239-149.ec2.internal phabricator:  ERROR 1044 (42000) at line 1: Access denied for user 'bn_phabricator'@'%' to database 'bitnami_phabricator_E5EBl'
```

The other error is this: 
```
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Phabricator has being initialized already, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error:
 ERROR 1045 (28000): Access denied for user 'bn_phabricator'@'172.20.0.3' (using password: YES)
```

**Comment by marcosbc** [comment]
Hi @ethicalmohit, currently the database is only created if Phabricator was not initialized yet.

We assume you are moving from a non-Bitnami container Phabricator, in which case you won't have a preconfigured volume and the database is external from the docker-compose deployment. If so, you can try the following:

- Launch a docker-compose deployment with the same values of MARIADB_USER, MARIADB_PASSWORD but not MARIADB_HOST for Phabricator, and a MariaDB container for that user.
- When it is initialized, enter the Phabricator container and edit the MariaDB hostname:

```
$ ./bin/config set mysql.host 'your.database.host'
```

- Stop the MariaDB container, delete it plus its volume, and remove it from docker-compose.yml.
- If you had any data, try to copy your existing Phabricator install data to the container at `/bitnami/phabricator/data` and `/bitnami/phabricator/repo`. But this might not work, so please **backup** before you try this.


It is important that you **don't delete the Phabricator volume**, as it will contain the file `/bitnami/phabricator/.initialized` which will determine if it was already initialized or not. If it does not exist, it will try to configure the database.

Hope it works!
