### ISSUE TITLE
Upgrade database schema?

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#12]
After upgrading a phabricator image (let's say: from `2016.31-r0` to `2016.40-r0`) shouldn't we also upgrade the databases schemas running `bin/storage upgrade` ?

**Comment by chipironcin** [comment]
Yes, Bitnami Phabricator Container should already be doing that with your persisted data from a previous version of Phabricator.
Are you experiencing any issue related to schema upgrade?

**Comment by fdcastel** [comment]
Nice to hear that. 👍 

I asked this because from my experience from #15 I had the impression this wasn't being done. I had to run `bin/storage upgrade` manually after I restored the databases. Simply starting the container after it wasn't enough.

But it was a long night 😄 and I was doing several tests at once until get "the right way". It was probably my fault, then. 😉

**Comment by fdcastel** [comment]
I'm reopening this one since, as reported in https://github.com/bitnami/bitnami-docker-phabricator/issues/41#issuecomment-274172209, an upgrade from a clean install of `2016.46-r4` to `2017.02-r0` didn't upgrade the database schema.

I had to explicitly call
```
/opt/bitnami/phabricator/bin/storage upgrade --force
```
inside the container.

**Comment by chipironcin** [comment]
Hi @fdcastel you are right!
Let us fix the issue for the next release. It should be ready during this week.
Thanks for reporting it :)

**Comment by juan131** [comment]
Issue fixed on new release 2017.04-​r0

**Comment by juan131** [comment]
@fdcastel  could please you confirm us that the issue is solved on the new release?

**Comment by fdcastel** [comment]
@juan131 I will try to upgrade my installation ASAP. Also, please see https://github.com/bitnami/bitnami-docker-phabricator/issues/41#issuecomment-276487020

**Comment by fdcastel** [comment]
I upgraded from `2017.02-r0` to `2017.04-r0` and it worked fine. 🙌 

According to [this](https://secure.phabricator.com/w/changelog/2017.03/#migrations) there is a database migration in `2017.03`, but I didn't run `storage upgrade` manually like in previous versions. The site just run fine after the image upgrade.

I'm closing this one. Thanks everyone! 👍

**Comment by prydonius** [comment]
Thanks for confirming @fdcastel!!
