### ISSUE TITLE
Failed deploy: standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Maxiride** [bitnami/bitnami-docker-phabricator#121]
Environment:
Raspberry Pi 3 B+ with docker and docker-compose
```
pi@raspberrypi:~/pihole/dnsmasq.d $ docker -v && docker-compose -v
Docker version 18.09.0, build 4d60db4
docker-compose version 1.8.0, build unknown
```

Issue:
I went straight with the _no brain_ setup by running the docker compose on the latest version of the repository as described [here](https://github.com/bitnami/bitnami-docker-phabricator#docker-compose).

However the ony information from the log is:
`standard_init_linux.go:207: exec user process caused "exec format error"`

I'd be more than happy to help investigate the issue as googling the error yelds very generic results unrelated to docker or even this particular image.

**Comment by Maxiride** [comment]
Seems like that your image doesn't support `arm` architectures if that's the case it should be mentioned in the readme of the repo.

**Comment by alemorcuq** [comment]
Hi, @Maxiride.

Yes, we currently don't support `arm` architectures. It's not in our short-term plans to support them, but [you are not the first one interested](https://github.com/bitnami/bitnami-docker-phabricator/issues/111). Thank you for showing your interest on it.

Regards,
Alejandro

**Comment by Maxiride** [comment]
@alemorcuq Thanks for the insight. I was reading through the docker-compose and dockerfile, am I right in saying that what prevents an arm deploy is the mariadb dependency?

From [the](https://secure.phabricator.com/book/phabricator/article/installation_guide/) Phabricator documentation the application itself can be run on arm devices, the other dependecies like PHP and Apache\Nginx have armhf compatible containers but only MariaDB isn't arm compatible.

I'm not a Docker expert at all but if you could please confirm my hypothesis or point me in the right direction I think I can manage to assemble a fork of bitnami/phabricator and switch to postgres db (which has an arm container available).

**Comment by Maxiride** [comment]
I deployed successfully Phabricator by simply switching to the [linuxserver/mariadb](https://hub.docker.com/r/linuxserver/mariadb) image which is `armhf` and `armv8` compatible.

**Comment by alemorcuq** [comment]
Thank you for letting us now, I'm glad you are able to run Phabricator on your Raspberry.
