### ISSUE TITLE
Can't download it to NAS Symology Docker.

### ISSUE THREAD

**Issue by VitaliyAT** [bitnami/bitnami-docker-phabricator#127]
Is it special or is it bug.
I open Docker on DSM 6.1 Synology NAS, push Download - got nothing.

**Comment by andresbono** [comment]
Hi @VitaliyAT, we have not tested the containers in a Synology NAS, so we can't tell you the reason of the issue. The Phabricator container image is just a regular container.

What is the OS architecture of the machine? Please note that it should be `amd64/linux`.
