### ISSUE TITLE
Site not found. This request asked for "/" on host <my-ip-address>, but no site is configured which can serve this request.

### ISSUE THREAD

**Issue by lcristianiim** [bitnami/bitnami-docker-phabricator#133]
Hello,
After following the following instructions:
``` sh
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-phabricator/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```
the project starts but when I access it from the browser I am getting the following:
```
This request asked for "/" on host <my-ip-address>, but no site is configured which can serve this request.
```
This is exactly what is happening if I don't use docker-compose.yml, but the `docker run ...` commands.

Is this a local issue from my side or there are some more steps & configuration that must be made?

**Comment by Alphapage** [comment]
Hello,
I have the same problem trying localhost or network ip, so I tried 127.0.0.1 which is working but give me ugly phabricator design.

**Comment by marcosbc** [comment]
Hi, you need to specify the `PHABRICATOR_HOST` environment variable if you want to access it outside of localhost, as it is set to `127.0.0.1` by default.

Could you check if setting it fixes your issues?

**Comment by Alphapage** [comment]
This was my first problem which solved my issue, but it seems phabricator doesn't support adding a custom port in url and which results in a ugly design.
I created a ticket to get more info about my problem: https://discourse.phabricator-community.org/t/add-support-to-other-port-in-url/3400

**Comment by marcosbc** [comment]
Hi @Alphapage, that is because the `base-uri` is set during the initialization. You can workaround it by running the command below (supposing you want to access at 127.0.0.1):

    /opt/bitnami/phabricator/bin/config set phabricator.base-uri http://127.0.0.1:8080

If you are using Docker Compose, you simply need to execute the command below in the folder with `docker-compose.yml`:

    docker-compose exec phabricator /opt/bitnami/phabricator/bin/config set phabricator.base-uri http://127.0.0.1:8080

**Comment by obbardc** [comment]
Setting `PHABRICATOR_HOST=localhost` and accessing over `http://localhost` results in an error (but accessing `http://127.0.0.1` works fine):

```
This request included an invalid "Host" header, with value "localhost:8083". Host headers must contain a dot ("."), like "example.com". This is required for some browsers to be able to set cookies.

This may mean the base URI is configured incorrectly. You must serve Phabricator from a base URI with a dot (like "https://phabricator.mycompany.com"), not a bare domain (like "https://phabricator/"). If you are trying to use a bare domain, change your configuration to use a full domain with a dot in it instead.

This might also mean that your webserver (or some other network device, like a load balancer) is mangling the "Host" header, or you are using a tool or library to issue a request manually and setting the wrong "Host" header.

Requests must include a valid "Host" header.
```

I guess this is an upstream issue.

**Comment by marcosbc** [comment]
Phabricator unfortunately requires a hostname to include a dot. However, if you use something such as "localhost.localdomain", ensuring it is set in /etc/hosts, it should also work.

**Comment by d33tah** [comment]
I'm confused. So what would be a working example of docker-compose.yml that lets me access the website locally? I just wanted to try phabricator out.

**Comment by dani8art** [comment]
Hi,

It should be one including `PHABRICATOR_HOST=localhost.localdomain`, then you should modify/add an entry to your `/etc/hosts` like

```
127.0.0.1   localhost.localdomain
```

Thanks!
