### ISSUE TITLE
phabricator repository update issue https://secure.phabricator.com/D20945

### ISSUE THREAD

**Issue by qxmips** [bitnami/bitnami-docker-phabricator#134]
**Description**
After one for upadtes having the issue updating repositories:
```
[2020-02-01 17:21:34] EXCEPTION: (Exception) Expected to find a Git repository at “/opt/bitnami/phabricator/repo/3/“, but there is a non-repository directory (with other stuff in it) there. Move or remove this directory. A daemon will construct the working copy for you. at [<phabricator>/src/applications/repository/engine/PhabricatorRepositoryPullEngine.php:346]
arcanist(head=stable, ref.stable=bac2028421a4), phabricator(head=stable, ref.stable=c4b4a53cad77), phutil(head=stable, ref.stable=1750586fdc50)
 #0 PhabricatorRepositoryPullEngine::executeGitUpdate() called at [<phabricator>/src/applications/repository/engine/PhabricatorRepositoryPullEngine.php:132]
 #1 PhabricatorRepositoryPullEngine::pullRepositoryWithLock() called at [<phabricator>/src/applications/repository/engine/PhabricatorRepositoryPullEngine.php:40]
 #2 PhabricatorRepositoryPullEngine::pullRepository() called at [<phabricator>/src/applications/repository/management/PhabricatorRepositoryManagementUpdateWorkflow.php:59]
 #3 PhabricatorRepositoryManagementUpdateWorkflow::execute(PhutilArgumentParser) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:457]
 #4 PhutilArgumentParser::parseWorkflowsFull(array) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:349]
 #5 PhutilArgumentParser::parseWorkflows(array) called at [<phabricator>/scripts/repository/manage_repositories.php:22]
```
the issue is sloved with this commit https://secure.phabricator.com/D20945
Tried to use the latest image but  the fix wasn't there.
could you add the code to the docker image?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @qxmips, thanks for letting us know. As soon as we release the version `2020.5`, it will include this fix.

**Comment by jimmybrancaccio** [comment]
I actually opened up a thread on the [Phabricator Discourse](https://discourse.phabricator-community.org/t/unable-to-create-an-observe-repository/3490/7) about this. It's been resolved in their stable branch.

@andresbono Any idea when `2020.5` will come about?

In the mean time, you can resolve it by going into `/opt/bitnami/phabricator/src/applications/repository/engine/` and doing a:

```
rm -fv PhabricatorRepositoryPullEngine.php
curl -O https://raw.githubusercontent.com/phacility/phabricator/stable/src/applications/repository/engine/PhabricatorRepositoryPullEngine.php
```

**Comment by andresbono** [comment]
Thanks for letting us know about this workaround, @jimmybrancaccio 

Sorry, we can't give you an ETA for Phabricator `2020.5`, but we will update this issue as soon as it gets released.

**Comment by jimmybrancaccio** [comment]
I'm pretty sure this is fixed now?

**Comment by andresbono** [comment]
Hi @jimmybrancaccio, yes this is already fixed. We didn't get to update the issue. Thanks for noticing.
