### ISSUE TITLE
Install python3-pygments For Pygmentize

### ISSUE THREAD

**Issue by jimmybrancaccio** [bitnami/bitnami-docker-phabricator#136]
**Description**

It looks like there's a couple open issues on this in the Debian bug tracker, but the solution is to install `python3-pygments` to get the `pygmentize` binary which is needed in Phabricator for syntax highlighting.

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918401
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919653

**Steps to reproduce the issue:**

1. Setup a new container using the Bitnami Phabricator image.
2. Log into Phabricator via a web browser.
3. Notice one of the warnings is about pygmentize missing.
4. Running `which pygmentize` will return nothing.

**Describe the results you received:**

See above 3 and 4.

**Describe the results you expected:**

There should be no warning about missing `pygmentize` in the Phabricator web UI and running `which pygmentize` should return something like:

``` shell
root@internal:~# which pygmentize
/usr/bin/pygmentize
```

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 22
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-29-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.36GiB
 Name: yoshi
 ID: PKRO:LFYL:KH4C:JQ76:A445:WHHR:5EWF:5AIE:AYP5:Z65K:5A4K:7RJH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jimmyb
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
N/A - unless if you need something specific

**Comment by marcosbc** [comment]
Hi, AFAIK this was implemented a couple of hours ago in the releases `2019.50.0-debian-10-r11` and `2019.50.0-ol-7-r53`, from https://github.com/bitnami/bitnami-docker-phabricator/pull/135. Could you try it out and let us know if it works?

**Comment by jimmybrancaccio** [comment]
Hey @marcosbc, almost! However, in the Phabricator web UI, I am seeing:

```
Phabricator has pygmentize available in $PATH, but the binary exited with an error code when run as pygmentize -h. Check that it is installed correctly.
```

and sure enough, running `pygmentize -h` on the command line gives me:

```
root@internal:/# pygmentize -h
Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

So I run `apt update` then `apt install python3-setuptools` and that seems to do the trick.

```
root@internal:/# pygmentize -h
Usage: /usr/bin/pygmentize [-l <lexer> | -g] [-F <filter>[:<options>]] [-f <formatter>]
          [-O <options>] [-P <option=value>] [-s] [-v] [-x] [-o <outfile>] [<infile>]
```

Not sure why, because the image is now basically doing what I was doing manually before, so it's a bit odd this `python3-setuptools` isn't there, but maybe that also needs to be added to the initial `apt install`?

**Comment by marcosbc** [comment]
Looking into this. Thank you for the PR!

**Comment by marcosbc** [comment]
@jimmybrancaccio Just wanted to let you know that Phabricator `bitnami/phabricator:2019.50.0-debian-10-r13` was released with the fix.
