### ISSUE TITLE
Version information is missing

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#14]
I tried to install a clean `2016.40-r0` image but unfortunately _Phabricator >  Config > Version Information_ shows nothing:

> **phabricator** Unknown 
> **arcanist** Unknown 
> **phutil** Unknown

I also tried to get the version directly from `/opt/bitnami/phabricator` using git commands but this path isn't a git working copy (probably the reason why phabricator can't show the versions).

Suggestion: to keep a git repository in phabricator/arcanist/phutil folder with `--depth 0` (shallow clone).

**Comment by chipironcin** [comment]
Hi @fdcastel;

Thanks for spotting this!
As you mention it seems we should keep the `.git` folder with the repo information because Phabricator will take its version from there.
The only drawback of this is that people could execute some git command over the files updating them and probably breaking the application.

We will try your suggestion of shallow clone and see if it fixes the issue.

**Comment by fdcastel** [comment]
> The only drawback of this is that people could execute some git command over the files updating them and probably breaking the application.

I understand. But... Hey! In this case... they asked for it, no? 😉.

Suggestion: to implement a git hook to block this? (But someone could say we are being a bit paranoid here 😅)

**Comment by chipironcin** [comment]
Hi again @fdcastel we found the issue pretty deep in the code so it may take a few days to reach Phabricator Nami module. (see https://github.com/bitnami/node-tarball-utils/issues/4)
Meanwhile, you can check what we ship taking a look at the official Phabricator changelog page:
https://secure.phabricator.com/w/changelog/

For example, for our Bitnami Phabricator v.2017.02-0, the version of the components can be retrieved from https://secure.phabricator.com/w/changelog/2017.02/

**Comment by fdcastel** [comment]
Solved in 2017.07. 👍

**Comment by sameersbn** [comment]
@chipironcin I noticed that the phabricator nami module now contains the complete git repo (~500MB). Did you check if the issue could be resolved by doing a shallow clone of the phabricator repo instead?

**Comment by chipironcin** [comment]
@sameersbn 
We are doing shallow clone of the Phabricator repo
```
root@00176a1eaab3:/# du -hs /opt/bitnami/phabricator/
188M	/opt/bitnami/phabricator/
```
can you open a new issue if it applies so we can track it better?
