### ISSUE TITLE
Need to set a "diffusion.allow-http-auth" via docker to be able to clone via https

### ISSUE THREAD

**Issue by Ani121293** [bitnami/bitnami-docker-phabricator#141]
**Description**
Getting 403 error while trying to clone the repo via https.
**based on https://docs.bitnami.com/installer/apps/phabricator/configuration/configure-hosted-repo/ Need to add a "diffusion.allow-http-auth" to be able to have a VCS password.**

Note: I have set it  the "diffusion.allow-http-auth" directly from docker sourced.

**Steps to reproduce the issue:**

1.Clonned the repo via https

**Describe the results you received:**
```git clone https://127.0.0.1/diffusion/4/ne.git
Cloning into 'ne'...
fatal: unable to access 'https://127.0.0.1/diffusion/4/ne.git/': The requested URL returned error: 403
```

Is there any way to do it with config yml file?

**Describe the results you expected:**
Need so set the "diffusion.allow-http-auth" from yml file.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea838
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.31GiB
 Name: MC-0253
 ID: A2OD:S6K4:CMJT:ZUUL:GTV6:BDDA:EET7:EZFR:Q3JT:K3AQ:4CCS:2466
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by juan131** [comment]
Hi @Ani121293 

As you said, there' no env var at this moment to modify that settting.

As you can check in the link below, Phabricator container will run any script you mount at `/docker-entrypoint-init.d`. Therefore, you can mount your custom script that modifies that (and any other) property in the configuration file.

- https://github.com/bitnami/bitnami-docker-phabricator/blob/master/2020/debian-10/rootfs/post-init.sh

Would that solution work for you?

**Comment by Ani121293** [comment]
fine, thanks @juan131.

**Comment by juan131** [comment]
You're welcome @Ani121293 ! Please do not hesitate to let us know if you require further assistance.
