### ISSUE TITLE
Unable to install ARC to work with Phabricator

### ISSUE THREAD

**Issue by superloopnetwork** [bitnami/bitnami-docker-phabricator#148]
I'm at the stage where I cannot run 'arc install-certificate'. It just won't connect.

I've changed the URI both in Phabricator and Arc... Set the domain to point to 'phabricator.superloop.center' but still refused to connect. I even set https.blindly-trust-domains to the same URI but no luck... Then I noticed something... and I'm not sure if this is the main issue that is causing this to not work. When I checked the self signed cert it's issued by and pointing to example.com. This is obviously the default from the docker. Would this be an issue?

![image](https://user-images.githubusercontent.com/23246145/83970864-04653300-a8a6-11ea-8f9b-7b10bdfe1c35.png)

I still don't understand why https.blindly-trust-domains doesn't work on hostname. I've seen two posts online of people experiencing the same. They've set it to blindly trust, but no luck as well.

If I were to generate a new self signed cert (low importance because I'm just running it at home), where would I dump the certificates? I just want to get pass this 'arc install-certificate' stage.

**Comment by marcosbc** [comment]
Hi @superloopnetwork, you're right. It looks like Phabricator is configured with HTTPS by default now:

```console
config get phabricator.base-uri
{
  "config": [
    {
      "key": "phabricator.base-uri",
      "source": "local",
      "value": "https://example.com",
      "status": "set",
      "errorInfo": null
    },
    {
      "key": "phabricator.base-uri",
      "source": "database",
      "value": null,
      "status": "unset",
      "errorInfo": null
    }
  ]
}
```

To avoid these issues, you can set the base URI to HTTP:

```console
$ config set phabricator.base-uri http://example.com
```

And then it should work:

```console
$ arc install-certificate
 CONNECT  Connecting to "http://example.com/api/"...
LOGIN TO PHABRICATOR
Open this page in your browser and login to Phabricator if necessary:

http://example.com/conduit/login/

Then paste the API Token on that page below.

    Paste API Token from that page: cli-4flcr55sborqbqbdhl6yogefuwl6
Writing ~/.arcrc...
 SUCCESS!  API Token installed.
```

We've traced this back to an old issue where HTTPS would not work, so it looks like we enabled HTTPS by default altogether, despite it not being configured for Docker images. We will look into adding support for an environment variable to use HTTP by default (but disabled by default), for simple use cases like yours.

>If I were to generate a new self signed cert (low importance because I'm just running it at home), where would I dump the certificates? I just want to get pass this 'arc install-certificate' stage.

If you mount the following files it should work:

* /certs/server.crt: Signed HTTPS certificate
* /certs/server.key: Key to the HTTPS certificate

**Comment by superloopnetwork** [comment]
Thank you so much! This fixed my issue! :)
