### ISSUE TITLE
Migration from Bitnami native install to docker

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#15]
A guide to migrate a Bitnami native install to a Bitnami docker would be very helpful for future users. 

I'm following the [Phabricator instructions](https://secure.phabricator.com/book/phabricator/article/configuring_backups/) but I did hit some bumps in the process.

**Comment by fdcastel** [comment]
To restore the database dump you will need to drop the initial databases (created on Phabricator first run)

1. `bin/phd stop`
2. `bin/storage destroy --force` **(this is important or the upgrade can fail)**
3. Restore mysql dumps
4. `bin/storage upgrade --force`
5. `bin/phd start`

**Comment by fdcastel** [comment]
After the database restore, I copied the hosted repositories from `/opt/phabricator/apps/phabricator/repo` folder in the native install to `/bitnami/phabricator/repo` folder in docker container. 

Also, I did the same for the local disk storage: I copied `/opt/phabricator/apps/phabricator/data` folder in the native install to `/bitnami/phabricator/data` folder in docker container. 

No problems here.

**Comment by fdcastel** [comment]
However, after all this, I can`t access my Diffusion repositories anymore. The web interface shows:

> **Unable to Retrieve Paths**
> File system entity '/opt/phabricator/apps/phabricator/repo/5/' does not exist.
> 
> **Unable to Retrieve History**
> File system entity '/opt/phabricator/apps/phabricator/repo/5/' does not exist.
> 
> **Unable to Load Tags**
> File system entity '/opt/phabricator/apps/phabricator/repo/5/' does not exist.
> 
> **Unable to Load Branches**
> File system entity '/opt/phabricator/apps/phabricator/repo/5/' does not exist.
> 

The full path for old repositories (`/opt/phabricator/apps/phabricator/repo`) is stored somewhere in the database and now I need to fix it. Where?

Through the web interface it's possible to see this setting (_Diffusion > (repository) > Manage > Storage_). But not to change it.

**Comment by fdcastel** [comment]
I did create a symlink to fix this:

```
mkdir -p /opt/phabricator/apps/phabricator
ln -s /bitnami/phabricator/repo/ /opt/phabricator/apps/phabricator/repo
```

Not a decent solution.  But a safe one, for now.

Now Diffusion is complaining that `git` command was not found. It is not on PATH?

**Comment by fdcastel** [comment]
Current path is

`/opt/bitnami/arcanist/bin:/opt/bitnami/php/bin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

I solved this one adding `/opt/bitnami/git/bin` to `environment.append-paths` setting.

```
bin/config set environment.append-paths '["/opt/bitnami/git/bin"]'
bin/phd restart
```

Aaaand now it is working! 😅

**Comment by fdcastel** [comment]
After some tests, I believe this is enough to update the repositories path:

```
USE bitnami_phabricator_repository;

UPDATE repository SET localPath = REPLACE(localPath, '/opt/phabricator/apps/phabricator/repo/', '/opt/bitnami/phabricator/repo/');

COMMIT;
```

This way there's no need to create symlinks for the old storage location.

**Comment by chipironcin** [comment]
Wow @fdcastel thanks for your research!
Definitely, a guide for migrating Phabricator data from a Bitnami Stack to a Bitnami Container would be very useful.
I will test your last suggestion but we are open to contributions. PRs are pretty welcome if you want to participate in this repo ;)
If not, I will update the documentation.
Cheers!

**Comment by fdcastel** [comment]
I will be glad to write about how to do this migration. 😄 

But where should we put this info? In README? In a new document? Or even in the new https://docs.bitnami.com/containers/ ?

**Comment by chipironcin** [comment]
In the README.md of this repository, under a title like `How to move from Bitnami Phabricator Stack to Bitnami Phabricator Container`

**Comment by juan131** [comment]
Linking PR: https://github.com/bitnami/bitnami-docker-phabricator/pull/44 with issue

**Comment by carrodher** [comment]
This guide looks great on the readme, seeing that it is merged, we will close the issue ok?
