### ISSUE TITLE
Translation of PHABRICATOR_HOST goes wrong

### ISSUE THREAD

**Issue by EricSalemi** [bitnami/bitnami-docker-phabricator#150]
**Description**

The `PHABRICATOR_HOST` translation logic to `phabricator.base-uri` is in my opinion unclear and somewhat buggy. Using `PHABRICATOR_HOST=127.0.0.1` translates to the unsecure URI `http://127.0.0.1` being set. Using `PHABRICATOR_HOST=myhost.mydomain` translates to the secure URI 'https://myhost.mydomain' being set. Using `PHABRICATOR_HOST=http://myhost.mydomain` translate to the invalid URI `https://[[http://myhost.mydomain]]` being set.

The problem here is that I cannot deploy the Phabricator instance with the `myhost.mydomain` over port 80 as the `phabricator.base-uri` gets translated to a secured uri starting with `https://`and that prevents me from logging in with the initial account setup via `PHABRICATOR_USERNAME`and `PHABRICATOR_PASSWORD`. I do get an Phabrictor error similar to https://phabricator.wikimedia.org/T165643.

**Steps to reproduce the issue:**

1. Use `PHABRICATOR_HOST` value of the form `http://myhost.mydomain`
2. Use `NAMI_LOG_LEVEL=trace8`

Executing `docker-compose up` and looking at the debug output gives:

```
phabricator_1  | phabric DEBUG Configuring Phabricator URL to: https://[[http://myhost.mydomain]]
phabricator_1  | phabric TRACE [runProgram] Executing: /opt/bitnami/phabricator/bin/config set,phabricator.base-uri,https://[[http://myhost.mydomain]]
phabricator_1  | phabric TRACE [runProgram] Executing internal command: /opt/bitnami/phabricator/bin/config ["set","phabricator.base-uri","https://[[http://myhost.mydomain]]"]
```

**Describe the results you expected:**

I would expect bitnami to allow me to use a `PHABRICATOR_HOST` value starting with `http://`and translate it to a valid non-secure URI for `phabricator.base-uri`. I am also surprised that bitnami somehow automatically adds an `https://` prefix when none is specified and forces me to use a secure setup which is in most cases complciated an unecessary.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: 53D2:Z4O4:ZIDG:QUNA:LMD2:7K6R:TM5L:OYKY:ISUV:CU2G:7QQ7:DGWR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 53
  System Time: 2020-06-20T08:44:53.7762741Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

`docker.io/bitnami/phabricator:2020-debian-10` image.
Docker for MAC.

**Comment by marcosbc** [comment]
Hi @EricSalemi, this is a known issue and related to this other case, which was apparently closed: https://github.com/bitnami/bitnami-docker-phabricator/issues/148

We already have an internal task for working on this, but unfortunately cannot give an ETA for when it will be fixed. In the meantime, if you manually set `phabricator.base-uri` after the initialization (like mentioned in the above issue) it should work for now, as the database is persisted between runs.

**Comment by EricSalemi** [comment]
I'm actually trying to automate this process for our continuous integration setup. Setting `phabricator.base-uri` at the right moment, i.e after the bitnami stack has set it up, turns out to be more difficult than I thought. I assume I should remove usage of the `PHABRICATOR_HOST` environment variable in my `docker-compose.yml` file because so far it looks like bitnami overwrites it whenever I do a down/up cycle.

**Comment by marcosbc** [comment]
Hi @EricSalemi, have you considered making use of init scripts?

If you mount a .sh script at `/docker-entrypoint-init.d` that updates the `phabricator.base-uri` property via the Phabricator `config` command, it should work without requiring any manual work.

Refer to [`post-init.sh`](https://github.com/bitnami/bitnami-docker-phabricator/blob/master/2020/debian-10/rootfs/post-init.sh) for more information (it's called directly from the container's [`app-entrypoint.sh`](https://github.com/bitnami/bitnami-docker-phabricator/blob/master/2020/debian-10/rootfs/app-entrypoint.sh) entrypoint).

**Comment by EricSalemi** [comment]
First I tried to do it by overriding the `ENTRYPOINT` but quickly gave up as I didn't find it clean at all (own image, wait for init phase to end, etc.). Your solution looks indeed exactly as what I need but only found out after I managed to do what I wanted with `gradle`. I'm currently using a liveness probe from docker gradle plugin to detect the end of the bitnami init phase. It's not the cleanest solution but works very well.

**Comment by marcosbc** [comment]
Thanks for sharing! In that case I'll consider this issue as solved. Let us know if that's not the case.

**Comment by EricSalemi** [comment]
For referecne this is what it looks like in my `build.gradle`:

```gradle
plugins {
    id 'com.avast.gradle.docker-compose'
    id 'com.bmuschko.docker-remote-api'
}


import com.bmuschko.gradle.docker.tasks.container.DockerExecContainer
import com.bmuschko.gradle.docker.tasks.container.extras.DockerLivenessContainer

import java.util.concurrent.TimeUnit

def PROJECT_NAME = 'the_name_of_your_compose_project'
def SERVICE_NAME = 'the_name_of_your_compose_service'
def POLL_DURATION = TimeUnit.MINUTES.toMillis(2)
def POLL_INTERVAL = TimeUnit.SECONDS.toMillis(10)
// Sentence below to catch when Phabricator is done initializating...
def LOG_CONTAINS = 'Started new daemon overseer'
def PHABRICATOR_HOST = 'http://yourhost.yourdomain'

task isPhabricatorLive(type: DockerLivenessContainer) {
    dependsOn composeUp
    targetContainerId "${PROJECT_NAME}_${SERVICE_NAME}_1"
    livenessProbe(POLL_DURATION, POLL_INTERVAL, LOG_CONTAINS)
}

task up(type: DockerExecContainer) {
    dependsOn isPhabricatorLive
    targetContainerId "${PROJECT_NAME}_${SERVICE_NAME}_1"
    commands.addAll(
            ['/bin/bash', '-c', "/opt/bitnami/phabricator/bin/config set phabricator.base-uri \"$PHABRICATOR_HOST\""] as String[])
}

task down {
    dependsOn(composeDown)
}
```
