### ISSUE TITLE
php: not found

### ISSUE THREAD

**Issue by ilegendary** [bitnami/bitnami-docker-phabricator#151]
**Description**

When I use the command "arc land"  it report an error.

**Steps to reproduce the issue:**

1. arc land

**Describe the results you received:**

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 6 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 382 bytes | 382.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: [2020-06-30 20:52:24] EXCEPTION: (CommandException) Command failed with error #127!
remote: COMMAND
remote: php -d variables_order=E -r 'echo json_encode($_ENV);'
remote: 
remote: STDOUT
remote: (empty)
remote:
remote: STDERR
remote: sh: 1: php: not found
remote:  at [<arcanist>/src/future/exec/ExecFuture.php:409]
remote: arcanist(head=stable, ref.stable=b689a8c78b6c)
remote:   #0 ExecFuture::raiseResultError(array) called at [<arcanist>/src/future/exec/ExecFuture.php:313]
remote:   #1 ExecFuture::resolvex() called at [<arcanist>/src/future/exec/execx.php:17]
remote:   #2 execx(string, string) called at [<arcanist>/src/utils/PhutilExecutionEnvironment.php:40]
remote:   #3 PhutilExecutionEnvironment::repairMissingVariablesOrder() called at [<arcanist>/support/init/init-script.php:104]
remote:   #4 __arcanist_init_script__() called at [<arcanist>/support/init/init-script.php:115]
remote:   #5 include_once(string) called at [/opt/bitnami/phabricator/scripts/init/lib.php:12]
remote:   #6 init_phabricator_script(array) called at [/opt/bitnami/phabricator/scripts/init/init-script.php:9]
remote:   #7 require_once(string) called at [/opt/bitnami/phabricator/scripts/__init_script__.php:3]
remote:   #8 require_once(string) called at [/opt/bitnami/phabricator/scripts/repository/commit_hook.php:34]
To http://192.168.20.44/diffusion/2/static-h5.git
 ! [remote rejected] 9848b95fcc20 -> master (pre-receive hook declined)
error: failed to push some refs to 'http://192.168.20.44/diffusion/2/static-h5.git'

 LOAD STATE  Restoring local state (to ref "master" at commit "882f884e9f1b").
[2020-07-03 09:58:19] EXCEPTION: (ArcanistUsageException) Push failed! Fix the error and run "arc land" again. at [<arcanist>\src\land\engine\ArcanistGitLandEngine.php:512]
arcanist(head=master, ref.master=4b8a32ee0273)
  #0 ArcanistGitLandEngine::pushChange(string) called at [<arcanist>\src\land\engine\ArcanistLandEngine.php:1260]
  #1 ArcanistLandEngine::execute() called at [<arcanist>\src\workflow\ArcanistLandWorkflow.php:344]
  #2 ArcanistLandWorkflow::runWorkflow(PhutilArgumentParser) called at [<arcanist>\src\workflow\ArcanistWorkflow.php:227]
  #3 ArcanistWorkflow::executeWorkflow(PhutilArgumentParser) called at [<arcanist>\src\toolset\ArcanistPhutilWorkflow.php:21]
  #4 ArcanistPhutilWorkflow::execute(PhutilArgumentParser) called at [<arcanist>\src\parser\argument\PhutilArgumentParser.php:492]
  #5 PhutilArgumentParser::parseWorkflowsFull(array) called at [<arcanist>\src\runtime\ArcanistRuntime.php:169]
  #6 ArcanistRuntime::executeCore(array) called at [<arcanist>\src\runtime\ArcanistRuntime.php:37]
  #7 ArcanistRuntime::execute(array) called at [<arcanist>\support\init\init-arcanist.php:6]
  #8 require_once(string) called at [<arcanist>\bin\arc:10]

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 137
 Server Version: 18.09.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.683GiB
 Name: localhost.localdomain
 ID: 4GSR:U5YB:RKFJ:SSGD:5K3S:TNPX:ZV3E:UUNY:TX7I:ROUV:IZQ3:IBAE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://451owsqa.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @ilegendary ,
Could you please elaborate the issue?

**Comment by miguelaeh** [comment]
Hi @ilegendary ,
thanks for editing the comment. Are you using the default Docker-compose file? Could you share your custom docker-compose? Also, could you exec into the container and check that is has `php` installing by executing `php --version` ?
Also, wich version of the image are you using?

**Comment by ilegendary** [comment]
Hi @miguelaeh 

**docker-compose.yml**

version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'docker.io/bitnami/phabricator:2020-debian-10'
    environment:
      - PHABRICATOR_HOST=192.168.20.44
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: loca

**php version**

[root@localhost codereview]# docker exec -it codereview_phabricator_1 bash
root@aa69c95f9e1d:/# php -v
PHP 7.3.19 (cli) (built: Jun 11 2020 12:11:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19, Copyright (c) 1999-2018, by Zend Technologies

**Comment by miguelaeh** [comment]
Hi @ilegendary ,
Are you executing the `arc` command inside the container or inside another machine? In the second cae, has that other machine installed PHP?

**Comment by ilegendary** [comment]
Hi @miguelaeh   
I execute `arc` command on the other machine which has already installed PHP.
Here is the PHP info.
```
PHP 7.4.7 (cli) (built: Jun  9 2020 13:34:30) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

```
```
remote: [2020-06-30 20:52:24] EXCEPTION: (CommandException) Command failed with error #127!
remote: COMMAND
remote: php -d variables_order=E -r 'echo json_encode($_ENV);'

```
It seems report an remote error when  execute the command  `php -d variables_order=E -r 'echo json_encode($_ENV);'` .

I try to deploy phabricator on CentOS not  container environment . It works well.

**Comment by miguelaeh** [comment]
It seems that the container has PHP `7.4` while you are using PHP `7.3` to run arc. I am not totally sure about what could be happening, is it possible in your case to test using the same PHP version as the container in the machine where you are executing `arc`?

**Comment by ilegendary** [comment]
Hi @miguelaeh 

```
<?php

/**
 * Get information about the current execution environment.
 */
final class PhutilExecutionEnvironment extends Phobject {

  public static function getOSXVersion() {
    if (php_uname('s') != 'Darwin') {
      return null;
    }

    return php_uname('r');
  }

  /**
   * If the PHP configuration setting "variables_order" does not include "E",
   * the `$_ENV` superglobal is not populated with the containing environment.
   * For details, see T12071.
   *
   * This can be fixed by adding "E" to the configuration, but we can also
   * repair it ourselves by re-executing a subprocess with the configuration
   * option defined to include "E". This is clumsy, but saves users from
   * needing to go find and edit their PHP files.
   *
   * @return void
   */
  public static function repairMissingVariablesOrder() {
    $variables_order = ini_get('variables_order');
    $variables_order = strtoupper($variables_order);

    if (strpos($variables_order, 'E') !== false) {
      // The "variables_order" option already has "E", so we don't need to
      // repair $_ENV.
      return;
    }

    list($env) = execx(
      'php -d variables_order=E -r %s',
      'echo json_encode($_ENV);');
    $env = phutil_json_decode($env);

    $_ENV = $_ENV + $env;
  }

}

```  

It seems that this file in the container report the error which path is `/opt/bitnami/arcanist/src/utils/PhutilExecutionEnvironment.php`.

**Comment by miguelaeh** [comment]
It is weird, the error seems to be that `php` is not in the `PATH` in the run time for that script. I mean, it cannot find the PHP binary to execute that command.
Could you give a try to modify that script and substitute the `php` call by the full path to the `php` binary? There is a variable in PHP called `PHP_BINARY` that returns the binary. Documented here: https://www.php.net/manual/en/reserved.constants.php
Or you can change it by the output of `which php`

**Comment by ilegendary** [comment]
Hi @miguelaeh 
I have change the code to output `PHP_BINARY` but I still can not find out the problem.

```
public static function repairMissingVariablesOrder() {
    $variables_order = ini_get('variables_order');
    $variables_order = strtoupper($variables_order);

    if (strpos($variables_order, 'E') !== false) {
      // The "variables_order" option already has "E", so we don't need to
      // repair $_ENV.
      return;
    }

    echo 'PHP_BINARY:'.PHP_BINARY."\n";
    echo 'variables_order:'.$variables_order."\n";

    list($env) = execx(
      'php -d variables_order=E -r %s',
      'echo json_encode($_ENV);');
    $env = phutil_json_decode($env);

    $_ENV = $_ENV + $env;
  }

```

```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 364 bytes | 364.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
**remote: PHP_BINARY:/opt/bitnami/php/bin/php
remote: variables_order:GPCS**
remote: [2020-07-10 03:58:56] EXCEPTION: (CommandException) Command failed with error #127!
remote: COMMAND
remote: php -d variables_order=E -r 'echo json_encode($_ENV);'
remote: 
remote: STDOUT
remote: (empty)
remote: 
remote: STDERR
remote: sh: 1: php: not found
remote:  at [<arcanist>/src/future/exec/ExecFuture.php:409]
remote: arcanist(head=stable, ref.stable=8795282286a7)
remote:   #0 ExecFuture::raiseResultError(array) called at [<arcanist>/src/future/exec/ExecFuture.php:313]
remote:   #1 ExecFuture::resolvex() called at [<arcanist>/src/future/exec/execx.php:17]
remote:   #2 execx(string, string) called at [<arcanist>/src/utils/PhutilExecutionEnvironment.php:43]
remote:   #3 PhutilExecutionEnvironment::repairMissingVariablesOrder() called at [<arcanist>/support/init/init-script.php:104]
remote:   #4 __arcanist_init_script__() called at [<arcanist>/support/init/init-script.php:115]
remote:   #5 include_once(string) called at [/opt/bitnami/phabricator/scripts/init/lib.php:12]
remote:   #6 init_phabricator_script(array) called at [/opt/bitnami/phabricator/scripts/init/init-script.php:9]
remote:   #7 require_once(string) called at [/opt/bitnami/phabricator/scripts/__init_script__.php:3]
remote:   #8 require_once(string) called at [/opt/bitnami/phabricator/scripts/repository/commit_hook.php:34]
To http://192.168.20.44/diffusion/2/static-h5.git
```

**Comment by miguelaeh** [comment]
Hi @ilegendary ,
The line you should change is `'php -d variables_order=E -r %s',` by `/opt/bitnami/php/bin/php -d variables_order=E -r %s'`

With the code you shared in your last comment you will just print a message in the output but that will not change the behaviour.

**Comment by ilegendary** [comment]
It works , but another problem has apear. I can use `git push` to directly commit my code without codereview.
When I use arc land it tells me land success ,but the state on phabricator has not change. 
I don't know if this changes casue this problem or not.

**Comment by joancafom** [comment]
Hi @ilegendary ,

Glad to see the changes worked! I did not fully understand the workflow for the new problem. Did you use `git push` and right after `arc land`? Can you provide me with some steps to follow in order to reproduce this new issue?

Thanks!

**Comment by jabdoa2** [comment]
Got the same issue in my instance. Is there a fix for this?

**Comment by miguelaeh** [comment]
Hi @jabdoa2,
Could you describe the workflow you are following?

**Comment by ipostanogov** [comment]
@miguelaeh,

1. Run a new instance.
1. Enable `diffusion.allow-http-auth`.
1. Add a new VCS password.
1. Create a new repository.
1. Push to that repository via HTTP.

You'll see an error similar to https://github.com/bitnami/bitnami-docker-phabricator/issues/151#issuecomment-656469889

P.S. As a temporary workaround one could add a symlink (`ln -s /opt/bitnami/php/bin/php /usr/bin/php`).

**Comment by miguelaeh** [comment]
Hi @ipostanogov ,
It seems that the path to the PHP binary is hardcoded, thank you for sharing your workaround!

**Comment by rinarchy** [comment]
Also have this - workaround works, however, any news on a fix?

**Comment by FraPazGal** [comment]
Hello @rinarchy,

We have applied the fix @ipostanogov suggested and it should be fixed in our new revision release. Thank you all for the patience!

**Comment by reutopiaer** [comment]
'php -d variables_order=E -r %s' at /opt/bitnami/arcanist/src/utils/PhutilExecutionEnvironment.php

not  at [<arcanist>/src/future/exec/ExecFuture.php:409]

**Comment by miguelaeh** [comment]
Hi @reutopiaer ,
Could you please elaborate on what are you trying to expose, please?
