### ISSUE TITLE
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'

### ISSUE THREAD

**Issue by RuslanAbdullaev** [bitnami/bitnami-docker-phabricator#153]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @RuslanAbdullaev, it looks like you opened the issue without filling the template describing the issue. Could you please make sure you give us more details about it?

**Comment by RuslanAbdullaev** [comment]
Hi @andresbono, last build fixed my problem
