### ISSUE TITLE
Allow configuration of VCS user

### ISSUE THREAD

**Issue by jpedrick** [bitnami/bitnami-docker-phabricator#158]
**Description**

Currently the VCS user is set to "git" and aspects of the VCS user are hard coded into the bitnami-pkgs, so altering this user is non-trivial even if you build your own docker image. In my use case, I am hosting a mercurial repository so 'git' is a little awkward to explain. An additional PHABRICATOR_SSH_VCS_USER environment variable to influence the diffusion.ssh-user would be helpful. 

An alternative, rename 'git' to 'vcs' or something that's independent from the repository type, since not everyone uses git.

**Comment by alemorcuq** [comment]
Hi, @jpedrick.

We will be adding a couple of environment variables to configure the VCS user and group. I will ping you when it's ready.

**Comment by alemorcuq** [comment]
I've added the two environment variables I mentioned:

- `PHABRICATOR_SSH_VCS_GROUP`: VCS group for SSH access. Default: **git**
- `PHABRICATOR_SSH_VCS_USER`: VCS user for SSH access. Default: **git**

Thanks for suggesting this feature, @jpedrick.

**Comment by jpedrick** [comment]
I just tried this out. I'm still seeing 'git' as the user in /etc/sudoers.d/phabricator
