### ISSUE TITLE
VCS ssh user should be added to sudoers

### ISSUE THREAD

**Issue by jpedrick** [bitnami/bitnami-docker-phabricator#159]
**Description**

/etc/sudoers.d/phabricator git user needs permission for /usr/bin/hg:

git ALL=(phabricator) SETENV: NOPASSWD: /opt/bitnami/git/bin/git, /opt/bitnami/git/bin/git-upload-pack, /opt/bitnami/git/bin/git-receive-pack, /usr/bin/hg

Pulling over ssh with mercurial doesn't work, because git user requires password for sudo actions. After modifying the above line in /etc/sudoers.d/phabricator it works as expected.

**Steps to reproduce the issue:**

1. setup phabricator with mercurial installed and PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY = yes
2. create mercurial repository
3. upload public key to user keys
4. clone mercurial repository using ssh://git@... URI
5. fail

**Describe the results you received:**

**What actually happens**

When pulling with mercurial over ssh I see:
hg clone ssh://git@phabricator.myhost.com/diffusion/4/myrepo/
remote: sudo: a password is required
abort: no suitable response from remote hg!

**What you expect to happen**

clone works

**Any additional information, configuration or data that might be necessary to reproduce the issue. **

Docker image: latest 2020-Nov-13

**Comment by FraPazGal** [comment]
Hi @jpedrick,

I think you are referencing to some code no longer present in the latest version of our image although you seem to be using the `latest` tag. In the new structure, `/usr/bin/hg` should be added to `ENV PATH` in the Dockerfile, could you confirm that would fix the issue?
