### ISSUE TITLE
Why 3 volumes?

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#16]
Instead of 

`VOLUME ["/bitnami/phabricator", "/bitnami/apache", "/bitnami/php"]`

Why not 

`VOLUME ["/bitnami"]`

?

**Comment by chipironcin** [comment]
Hi @fdcastel;
We decided to separate the volumes per item so they can be reused individually.
If you don't want to persist Apache configuration just don't mount that volume, but the others components will.

This structure is also more simple from an internal point of view and helps us to make some useful checks. If the volume is empty we initialize the component with default sample files, but if the volume contains files it means we should not overwrite them. Using a single volumewill complicate single component persistence checks.

**Comment by fdcastel** [comment]
I see your points. Thanks for the explanation.

I asked this as a first reaction just after I saw three distinct volumes (`apache-data`, `phabricator-data`, `php-data`) all mounted in the same root folder (`/bitnami/apache`, `/bitnami/phabricator`, `/bitnami/php`). So, I was wondering, why not to use just one (`bitnami-data`) for the root folder (`/bitnami`)?

Looking as a user from outside I really think a single volume would be better. However, I don't have the experience nor the several use cases you guys have to support. So, I bet you have good reasons to do it this way 😉.
