### ISSUE TITLE
install ncurses-bin package

### ISSUE THREAD

**Issue by jpedrick** [bitnami/bitnami-docker-phabricator#160]
**Description**

ncurses-bin package is missing, which is required by some phabricator scripts.

While reparsing a repository an error message comes up. I don't know the consequences.

root@phabricator-5bc9fb69-dqps8:/# repository reparse --all R2 --message  
sh: 1: tput: not found
...

**Steps to reproduce the issue:**

1. create mercurial repository
2. "repository reparse --all RXYZ --message"

**Describe the results you received:**

Error message, but process continues

**Describe the results you expected:**

No error message

**Comment by juan131** [comment]
Hi @jpedrick 

Thanks so much for reporting this issue! We'll release a new version of the image including the `ncurses-bin` package. 

We'll keep you updated about our progress!

**Comment by juan131** [comment]
Hi @jpedrick 

A new version was released including the package. See:

- https://github.com/bitnami/bitnami-docker-phabricator/commit/89cb5bceca23294902fde48ce699ac3ccbc79a00

You can give it a try running:

```console
$ docker run --rm -it bitnami/phabricator:2020.42.0-debian-10-r26 which tput
/usr/bin/tput
```
