### ISSUE TITLE
Unhandled Exception ("RuntimeException")

### ISSUE THREAD

**Issue by h77626592** [bitnami/bitnami-docker-phabricator#162]
![图片](https://user-images.githubusercontent.com/53549152/103837024-bf1c1480-50c5-11eb-8fad-2436ebe125e0.png)
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

bitnami/phabricator latest version

Abnormal error in modifying password

Help me, thank you

**Comment by juan131** [comment]
Hi @h77626592 

I was unable to reproduce the issue, are you using any special characters in the new password you chose?

**Comment by h77626592** [comment]
@juan131 Hello, the password is a combination of numbers and letters, no special characters

Can I see your create container command?

**Comment by h77626592** [comment]
docker run -d --name phabricator -p 443:443   \
	--link mysql:mysql \
	-v /phabricator:/bitnami \
	--env PHABRICATOR_USERNAME=admin \
	--env PHABRICATOR_PASSWORD=aaa1234 \
	--env MARIADB_USER=root \
	--env MARIADB_PASSWORD='aaa1234' \
	--env MARIADB_HOST=mysql \
	--env MARIADB_PORT_NUMBER=3306 \
    bitnami/phabricator:latest

Any problems?

**Comment by juan131** [comment]
Hi @h77626592 

I was using the sample DockerCompose (see https://github.com/bitnami/bitnami-docker-phabricator/blob/master/docker-compose.yml), but I don't see anything strange in the command you shared.

Are you able to reproduce the issue when using a MariaDB database (instead of MySQL)?
