### ISSUE TITLE
Missing mysqldump

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#17]
Trying to run a `bin/storage dump` in `2016.40-r0` gives the error:

`sh: 1: mysqldump: not found`

Please add `mysqldump` to `/opt/bitnami/mysql/bin` -- It is very useful for migrations and backups.

**Comment by chipironcin** [comment]
Thanks for reporting it @fdcastel 
We will take a look at it and ship if possible. I will let you know.
Cheers

**Comment by chipironcin** [comment]
Hi @fdcastel 
We are now shipping `mysqldump` binary in the `mysql-client` package.
That change can be tracked at PR #21 
Nevertheless, usage of `bin/storage dump` won't work out of the box as you should specify `mysqldump` where the database is (host and port).

You can write a file at `/opt/bitnami/mariadb/conf/my.cnf` with those details under the `[client]` section of mysql configuration for the Phabricator command to work.

We will document this in the README.md. Meanwhile you can try the solution above and see if it works for you :)

**Comment by sameersbn** [comment]
Thanks for taking the time to report this issue @fdcastel . The issue has been resolved since revision `2016.44-r0`.
Please reopen issue if the problem persists.
