### ISSUE TITLE
support for the raspberry pi 4

### ISSUE THREAD

**Issue by cooperspencer** [bitnami/bitnami-docker-phabricator#170]
is it possible to create a docker container for the raspberry pi 4, since the minideb image is now also available for the raspberry pi 4?
If there's anything where I can help out, just let me know.

**Comment by carrodher** [comment]
Minideb already supports ARM multi-arch which is a little step in that direction, but unfortunately, I cannot give any ETA for when ARM images will be available yet, as we currently have a lot of things on our plate which is causing work on this specific project to get delayed
