### ISSUE TITLE
No user exists for uid 1001 when running ssh-keygen

### ISSUE THREAD

**Issue by Camouflager** [bitnami/bitnami-docker-phabricator#174]
Thanks in advance for this wonderful work, and sorry for not following the template.

It took me a while to eventually track this down. When I try to add a new ssh private key credential for my git repository. It keeps reporting that the private key could not be opened. But I confirmed multiple times that the private key is valid. Eventually I managed to print out the error when phabricator is checking the key (it checks the key by ssh-keygen -y). And it says 'No user exists for uid 1001'.

Seems like ssh-keygen won't execute without a valid user? I wonder if there's any quick way around this. Any help is appreciated.

**Comment by alemorcuq** [comment]
Hi, @Camouflager.

Are you running Phabricator as a self hosted git repository? If so, running the container as root will create some users needed for it to work properly. Also, check the environment variables available for it: https://github.com/bitnami/bitnami-docker-phabricator#user-and-site-configuration

If on the other hand you are not running it as a self hosted git repository, I think your best option would be to extend the image to add a user for uid 1001. The reason why we can't add a user for uid 1001 is that some container platforms such as Openshift use random uids to run the containers.

**Comment by Camouflager** [comment]
I'll try to extend the image. Thanks
