### ISSUE TITLE
Dokcerfile is just for Phabricator image?

### ISSUE THREAD

**Issue by poetman** [bitnami/bitnami-docker-phabricator#26]
Hi.
I cloned this repository, and executed successfully.
But i wonder the instruction of command line 3 step execution.
Before run container, correct image should be exist, but not in cloned directory.
So, i think the Docker file is for making Image. 
Am i right? If yes, how to build 2 images with 1 Dockerfie.
Thanks in advance.
Poetman.

**Comment by chipironcin** [comment]
Hi @poetman 
The Dockerfile available in this repo is for building the Phabricator container.
It will contain the Phabricator application + Apache + PHP

To deploy Phabricator successfully we will need the Phabricator image and the MariaDB image so we can have one container with the application and another container with the database.

In this repo we ship the Dockerfile to build the Phabricator image and run a Phabricator container.

In this repo we also ship a docker-compose file that makes use of the latest Phabricator image published in Dockerhub and the latest MariaDB image published in Dockerhub to bring up two containers and make the application work.

You can find the Dockerfile to build the MariaDB image and run a MariaDB container in bitnami/bitnami-docker-mariadb

Does this description solve your doubts?
Regards ;)

**Comment by poetman** [comment]
Hi. chipironcin.

I definitely understood.
This github is very helpful for me.
Thanks for your explanation.
Poetman.
