### ISSUE TITLE
sh: 1: tput: not found

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#43]
As reported in https://github.com/bitnami/bitnami-docker-phabricator/issues/41#issuecomment-274172209 as of `2017.02-r0` some phabricator commands are outputting the error:

```
sh: 1: tput: not found
```

often during some long-running process (which displays a progress bar).

Some commands known to reproduce this error are:

```
bin/storage upgrade --force
bin/search index --all --force --background
```

**Comment by prydonius** [comment]
tput is a command used to calculate width and height of a terminal window, so this is probably used to try and calculate the width of the progress bar. Our containers don't include the command as we use a minimal base image, but assuming those commands ignore the tput error (which it looks like they do), this should be fine. Perhaps a bug needs to be filed upstream for those commands to silently ignore this error.

**Comment by fdcastel** [comment]
Sadly, I went to file this as a bug in Phabricator's Manifest but stopped due #14 😢

They require version information to submit a bug which I can't provide.

**Comment by juan131** [comment]
Closing because it seems to be Phabricator issue.

@fdcastel reopen it if you encounter more related problems.
