### ISSUE TITLE
Backup instructions not telling how to backup MariaDB databases

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#47]
Shouldn't the "Backing up your application" and "Restoring a backup" sections from `README.md` tell about how to backup (and restore) the MariaDB databases from Phabricator?

**Comment by prydonius** [comment]
+1

**Comment by juan131** [comment]
I let you some comments on PR  https://github.com/bitnami/bitnami-docker-phabricator/pull/48. Thanks for contributing!
