### ISSUE TITLE
HTTPS support / Let’s Encrypt

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#57]
I'm using this image behind a [nginx-proxy](https://github.com/jwilder/nginx-proxy) reverse firewall and with a little help from [nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) I got automatic [Let’s Encrypt](https://letsencrypt.org) certificates setup and running with no effort (including automatic renewals).

This works very well. The only inconvenience is that it adds a little overhead (2 extra containers). Also, the server must be publicly accessible and have a registered domain name (since Let’s Encrypt CA must call it).

That said,

1. Would you like me to write a new section in README detailing the instructions about how to make this setup?

2. There are some plans to support a similar setup "natively"? (i.e. to provide automatic HTTPS certificates configuration using Let’s Encrypt?). I'm asking this because IMHO if done in the lower levels (`nami` tool?) it could be a huge benefit for several other Bitnami applications (e.g. WordPress).

**Comment by dbarranco** [comment]
Thanks for the feedback @fdcastel, adding let's encrypt support natively sounds a great idea! 
We'll take this into account.

**Comment by fdcastel** [comment]
> it seems you have made a big effort to achieve it!

Actually, it was very straightforward. :) These projects (nginx-proxy and nginx-proxy-companion) are excellent. Simply set some environment vars and you are done. 

There are, however, some extra steps to watch with phabricator. I will try to compile them here.

**Comment by fdcastel** [comment]
For reference, these are the steps I'm doing. I hope it could help you somehow. Or any other user who wishes to make a similar setup, meanwhile.

This will setup a Bitnami Phabricator instance behind a HTTPS nginx proxy. It will request certificates for Let's Encrypt and will update them automatically. For more information, please see [nginx-proxy](https://github.com/jwilder/nginx-proxy) and [nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) project pages.

Run the following commands in an elevated `bash` prompt. You can just copy & paste them.

1. Start with some variables:

    ```bash
    # Your docker-compose.yml location
    SITE_DIR=/opt/bitnami-phabricator

    # Your Phabricator public address
    SITE_URL=myphabricator.CHANGE-ME.com

    # Your email address for Let's Encrypt
    CERTIFICATES_EMAIL=certificates@CHANGE-ME.com
    ```

    Important: The DNS address in `SITE_URL` must resolve to the computer you´re installing.

    In `CERTIFICATES_EMAIL` put an email address you check often (Let's Encrypt will warn you through it if your certificate are expiring -- just in case anything broke 😉).

2. Create directories and `docker-compose.yml` file:

    ```bash
    mkdir -p $SITE_DIR/certs
    mkdir -p $SITE_DIR/vhost.d
    mkdir -p $SITE_DIR/html

    cat > $SITE_DIR/docker-compose.yml <<EOF
    version: '2'

    services:
      proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - $SITE_DIR/vhost.d:/etc/nginx/vhost.d
          - $SITE_DIR/certs:/etc/nginx/certs:ro
          - $SITE_DIR/html:/usr/share/nginx/html
        networks:
          - public

      proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: proxy-companion
        volumes:
          - $SITE_DIR/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
          - proxy

      mariadb:
        image: bitnami/mariadb:latest
        container_name: mariadb
        volumes:
          - mariadb_data:/bitnami/mariadb
        networks:
          - private

      phabricator:
        image: bitnami/phabricator:latest
        container_name: phabricator
        environment:
          - VIRTUAL_HOST=$SITE_URL
          - LETSENCRYPT_HOST=$SITE_URL
          - LETSENCRYPT_EMAIL=$CERTIFICATES_EMAIL
          - PHABRICATOR_HOST=$SITE_URL
        depends_on:
          - mariadb
        expose:
          - 80
        volumes:
          - phabricator_data:/bitnami/phabricator
          - apache_data:/bitnami/apache
          - php_data:/bitnami/php
        networks:
          - public
          - private

    volumes:
      mariadb_data:
      phabricator_data:
      apache_data:
      php_data:

    networks:
      public:
      private:
    EOF
    ```

3. Start containers and follow the logs. **Wait until the initial setup is done**:
    ```bash
    cd $SITE_DIR
    docker-compose up -d
    docker logs phabricator -f
    ```

4. Set some initial settings and stop the containers:

    ```bash
    CONFIG="docker exec phabricator /opt/bitnami/phabricator/bin/config"
    
    # Set base uri
    $CONFIG set phabricator.base-uri https://$SITE_URL
    
    # Allows access to repositories only via https
    $CONFIG set security.require-https 'true'

    # Stop containers
    docker-compose down
   ```

5. Edit `docker-compose.yml` and add the following line in `services:` > `phabricator:` > `volumes:`
    ```yml
    - ./preamble.php:/opt/bitnami/phabricator/support/preamble.php
    ```

6. Start containers:
    ```bash
    docker-compose up -d
    ```

7. Create `preamble.php` file inside the container:
    ```bash
    (docker exec -i phabricator bash -c "cat > /opt/bitnami/phabricator/support/preamble.php")<<'EOF'
    <?php
    
    $_SERVER['HTTPS'] = true;
    EOF
    ```

8. Restart phabricator

    ```bash
    docker-compose restart phabricator
    ```

And you're done! 

Important: **The `preamble.php` file (steps 5~7) should not exist during the initial setup (step 3)** or you will get an `ELOOP: too many symbolic links encountered` error. Please see #41 for more information.

**Comment by dbarranco** [comment]
Hi @fdcastel 

That's awesome! 
Thank you so much for sharing that with us, we will take a look at it.

Best regards!

**Comment by akolnoochenko** [comment]
@fdcastel , is it possible to get values of phabricator config variables from preamble.php? Something like

```
if (GET_CONFIG_VALUE('security.require-https'))
{
    $_SERVER['HTTPS'] = true;
}
```

In that case it could be possible to mount preamble.php and eliminate the need in recreation of container.

**Comment by tompizmor** [comment]
Hello @akolnoochenko, @fdcastel 

We have released Phabricator 2018.3.0-r1 including a setting in the Apache configuration that helps when phabricator is behind a LoadBalancer. The configuration is `SetEnvIf X-Forwarded-Proto https HTTPS=on`.

With this apache configuration, the use of the preamble.php script is not necessary.

**Comment by SimZor** [comment]
How can I make this persistent so data is not lost if I remove the containers?

**Comment by tompizmor** [comment]
Hi @SimZor, which is the data that you would like to persist?
By default the persisted folders for phabricator are `/opt/bitnami/phabricator/data`, `/opt/bitnami/phabricator/conf` and `/opt/bitnami/phabricator/repo`.

Did you execute the following commands to configure phabricator to use https?

```
# Set base uri
docker exec phabricator /opt/bitnami/phabricator/bin/config set phabricator.base-uri https://$SITE_URL

# Allows access to repositories only via https
docker exec phabricator /opt/bitnami/phabricator/bin/config set security.require-https 'true'
```
Also, for newer versions of phabricator (since 2018.3.0-r1), the preamble.php step is not needed.
