### ISSUE TITLE
Why Apache?

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#61]
Given that 

- Phabricator [supports nginx](https://secure.phabricator.com/book/phabricator/article/configuration_guide/#webserver-configuring-ng); 
- Bitnami already has a nice [nginx image](https://github.com/bitnami/bitnami-docker-nginx); and
- any devop out there and their dog knows that [Apache is a resource hog](https://www.rootusers.com/linux-web-server-performance-benchmark-2016-results)

I would like to ask...

![Why?](https://media.giphy.com/media/cPKWZB2aaB3rO/giphy.gif)

Jokes aside 😅 I can see [in `Dockerfile`](https://github.com/bitnami/bitnami-docker-phabricator/blob/master/2017/Dockerfile#L20) this image just unpacks the upstream Bitnami Phabricator package and probably the cause is in there.

But I'm really curious to know what would be needed to make this happen.

There are some plans to support a nginx install? Are the sources for the above cited Phabricator pkg publicly available?

**Comment by javsalgar** [comment]
Hi, 

We use Apache with mod_php so a single process `httpd` is spawned in the container. Using Nginx and PHP-FPM is something we are looking into, but it is not trivial (either having multiple processes or separate container for nginx and php brings challenges that need to be tackled). Therefore, there are no short-term plans to support a nginx install.

However, we will update this thread in case there are news on this. Stay tuned!  :)
