### ISSUE TITLE
Observing git repo via ssh

### ISSUE THREAD

**Issue by BrendanSimon** [bitnami/bitnami-docker-phabricator#66]
I am new to docker and have installed Docker for Mac, retrieved `docker-compose.yml` with curl, and then ran `docker-compose up`.  That seems to work fine and I can access Phabricator with my browser :)

However I can't seem setup a repository to observe an existing git repo via ssh.  It seems an ssh client is not installed (also reported in #55).

The repo is actually stored on a NAS device and users access it directly (git CLI or SourceTree).  Phabricator wont let me access it directly, however I do have ssh access to it via our RaspberyPi SSH gateway (the NAS shares are mounted onto the Raspbian filesystem).

* Why is a ssh client not installed?
* Could the docker image be update to have an ssh client installed please :)

The following instructions are stated in #55 

```
apt-get update
apt-get install openssh-client
mkdir /home/phabricator
mkdir /home/phabricator/.ssh
```

Is that all is required?  How do I get to a bash prompt?  `docker-composer run bash` ??

Does the `/home/phabrictor` directory need to have the correct user and group IDs?

NOTES:

* Before using Docker, I tried the Bitnami Mac download and it worked fine (in that it didn't complain about ssh (I couldn't access my repo but that is probably another issue).

* Configuring the repo URIs was different between the two images (docker v mac).  The Docker image seem to provide a list of 3 default URIs, which I couldn't delete.  The Mac image had zero URIs and I just added what I needed.  I'm not quite sure what the affect of the 3 default URIs are when using Observe URIs.

Thanks, Brendan.

**Comment by carrodher** [comment]
Hi,

We do not install ssh by default since it is not an essential requirement for the operation of the application, but if it has a high demand we will consider adding it by default.

To connect to the container you can execute:
```bash
docker ps
```
And you will get an output like this:
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                      NAMES
e819556210fa        bitnami/phabricator:latest   "/app-entrypoint.s..."   17 minutes ago      Up 17 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   tmp_phabricator_1
3bf363e93948        bitnami/mariadb:latest       "/app-entrypoint.s..."   18 minutes ago      Up 17 minutes       3306/tcp                                   tmp_mariadb_1
```
Using the CONTAINER_ID of phabricator, you can run the next command:
```bash
docker exec -it CONTAINER_ID bash
```
Once inside the container you can install ssh-client using:
```bash
apt update
apt install openssh-client
mkdir /home/bitnami/.ssh
chown -R bitnami:bitnami /home/bitnami/.ssh
```

In your Mac, it works without installing ssh-client because you have installed it on your Mac, this is separate from the Bitnami Phabricator stack.

Best regards,
Carlos R. Hernández

**Comment by meros** [comment]
I think this is a pretty good thing to have by default. It cost me a few hours to figure out why ssh keys didn't work and how to get it working...

**Comment by sameersbn** [comment]
@BrendanSimon The ssh client has been add in [2017.15-r1](https://github.com/bitnami/bitnami-docker-phabricator/releases/tag/2017.15-r1). Could you please upgrade to this release and let us know if it fixes the issue for you?

**Comment by BrendanSimon** [comment]
Ok.  My first time with docker and phabricator.  How do I upgrade the container? (I'm using Docker for Mac if that makes any difference)

I tried the following but it didn't work (presumably not the correct method)

`docker-compose -f phabricator-docker-componse.yml up -d --no-deps --build phabricator`

and:

`docker-compose -f phabricator-docker-componse.yml up -d --no-deps --build phabricator`

**Comment by BrendanSimon** [comment]
Don't worry.  I found the instructions on the github page (blush)

**Comment by sameersbn** [comment]
Thanks @BrendanSimon 
Closing the issue, please re-open if the problem persists.
