### ISSUE TITLE
Preconfigured PHPExcel

### ISSUE THREAD

**Issue by BrendanSimon** [bitnami/bitnami-docker-phabricator#67]
Please include the `PHPExcel` classes and configuration so that exporting to Excel, LibreOffice, CSV, etc just works out of the box.

Thanks :)

**Comment by carrodher** [comment]
Hi,

Thanks for the suggestion, it is difficult to include all the modules that can be installed, if the number of requests is high then we consider its introduction.

Anyway, [here](https://github.com/PHPOffice/PHPExcel/blob/1.8/Documentation/markdown/Overview/01-Getting-Started.md) you will find how to install and configure PHPExcel.

Best regards,
Carlos R. Hernández
