### ISSUE TITLE
what happened to the repo?

### ISSUE THREAD

**Issue by hazaveh** [bitnami/bitnami-docker-phabricator#69]
> This repository doesn’t have any branches.
> This message will go away once a branch is created.
> If you think you received this message in error, please contact support.

Seems like all the branches are removed from the repo. I was using it yesterday and late at night repo stopped working.

**Comment by juan131** [comment]
@hazaveh thanks for reporting it. We don't know the reason why it was shown as an empty repo. 
Maybe an issue on GitHub side.

I was able to clone the repo even when it was supposed to be empty. Anyway, now it seems to be recovered. Sorry for the inconveniences.

I proceed to close the issue, please reopen it if that happens again.
