### ISSUE TITLE
Problems with permissions in data folder

### ISSUE THREAD

**Issue by meros** [bitnami/bitnami-docker-phabricator#70]
I get:

```
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000] [2017-04-26 09:48:49] EXCEPTION: (PhutilProxyException) Error while executing Task ID 103403. {>} (PhutilAggregateException) All storage engines failed to write file:
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000]     - PhabricatorLocalDiskFileStorageEngine: CommandException: Command failed with error #1!
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000]       COMMAND
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000]       mkdir -p '/opt/bitnami/phabricator/data/29/14'
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000]       
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:51 +0000]       STDOUT
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]       (empty)
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]       
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]       STDERR
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]       mkdir: cannot create directory '/opt/bitnami/phabricator/data/29': Permission denied
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]        at [<phabricator>/src/applications/files/storage/PhabricatorFile.php:362]
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000] arcanist(head=stable, ref.stable=3512c4ab86d6), phabricator(head=stable, ref.stable=517372a1e0c4), phutil(head=stable, ref.stable=7c7b02216f33)
Daemon 371 STDE [Wed, 26 Apr 2017 09:48:52 +0000]   #0 <#3> ExecFuture::resolvex() called at [<phutil>/src/future/exec/execx.php:17]
```

This is causing individual commits to hang in non-imported state once in a while.

**Comment by chipironcin** [comment]
Hi @meros 
Can you provide more info about your deployment?
How did you launch the container
Docker version

Also, can you list the permissions the folder `/opt/bitnami/phabricator/data` has inside the container?

**Comment by meros** [comment]
I will make sure to fill out the template in the future. Sorry about that lapse.

I cannot pin down steps to reproduce, but I first saw the issue after including a large repo (a fork of react-native) as an observed repo. Some of the commits never finished.

These are my permissions in the phabricator folder
```
drwxr-xr-x   5 root        root        4096 Apr 19 07:29 conf
drwxrwxr-x 109 daemon      daemon      4096 Apr 26 09:52 data
drwxr-xr-x   6 phabricator phabricator 4096 Apr 21 09:14 repo
```

in the data folders it's a mix

```
drwxrwxr-x   3 daemon daemon 4096 Apr 19 09:05 62
drwxr-xr-x   4 daemon daemon 4096 Apr 21 13:50 68
drwxr-xr-x   3 daemon daemon 4096 Apr 20 12:51 69
drwxr-xr-x   4 daemon daemon 4096 Apr 24 06:01 6b
drwxrwxr-x   3 daemon daemon 4096 Apr 19 08:34 6d
drwxr-xr-x   3 daemon daemon 4096 Apr 25 12:35 70
drwxr-xr-x  55 daemon daemon 4096 Apr 21 18:11 71
```

NB I might have fiddled with the permissions, since I have tried to 'fix' this problem on my own. If I understans correctly, this folder is for the file storage engine? And it needs to be writable by daemon? Does it need to be writable by phabricator user as well?

* Output of docker version:
```
Docker version 1.12.6, build 78d1802
```
* Output of docker info:
```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 39
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-46-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 11.69 GiB
Name: phabricator
ID: 7WC6:5IU3:S33R:ZTPK:LP3G:DXJS:ICAY:W4II:EFSD:UWUL:MXQ6:GB6E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```
* Output of docker-compose version (if applicable):
```
docker-compose version 1.8.0, build unknown
```

**Comment by meros** [comment]
Currently I am using mysql engine as a workaround, no more problems yet...

**Comment by chipironcin** [comment]
Hi @meros 
I cannot reproduce the issue.
These are the permissions by default in a working Phabricator container:
```
root@e23e97f4b72d:/# ls -la /bitnami/phabricator
total 20
drwxr-xr-x 5 root        root        4096 Apr 28 14:31 .
drwxr-xr-x 5 root        root        4096 Apr 28 14:30 ..
-rw-r--r-- 1 root        root           0 Apr 28 14:31 .initialized
drwxr-xr-x 5 root        root        4096 Apr 28 14:31 conf
drwxr-xr-x 3 daemon      daemon      4096 Apr 28 14:31 data
drwxr-xr-x 2 phabricator phabricator 4096 Apr 28 14:31 repo
root@e23e97f4b72d:/# ls -la /bitnami/phabricator/data
total 12
drwxr-xr-x 3 daemon daemon 4096 Apr 28 14:31 .
drwxr-xr-x 5 root   root   4096 Apr 28 14:31 ..
drwxr-xr-x 3 daemon daemon 4096 Apr 28 14:31 1b
```

Could you please set the permissions to match the default ones?
Also, pull the latest version of Phabricator container (`docker pull bitnami/phabricator:latest`) and update your deployment.

If after that it still doesnt work try giving `phabricator` user write permissions over `data`:
    chown -R daemon:phabricator /bitnami/phabricator/data     
    chmod -R 775 /bitnami/phabricator/data

Also, could you clarify this sentence?
>Currently I am using mysql engine as a workaround, no more problems yet...

**Comment by meros** [comment]
> Currently I am using mysql engine as a workaround, no more problems yet...
I meant that I switched to mysql as file storage engine, and that I have not gotten this problem since. I will set my file permissions to the suggested and report if we run into this again.

**Comment by amosbird** [comment]
Same error. I have to manually run
```
chown -R daemon:phabricator /bitnami/phabricator/data
chmod -R 775 /bitnami/phabricator/data
```

**Comment by juan131** [comment]
Hi @amosbird 

Could you provide the information below?

 - What version of this Docker Image are you using? 
 - Did you have to fix the ownership after creating a new container?
 - What kind of volume did you use for the persisted data? Is it a Docker volume or did you mount a directory from the host?

**Comment by tinder-maxwellelliott** [comment]
This should not be closed, we reproduced this issue as of today on `bitnami/phabricator:latest`

https://github.com/bitnami/bitnami-docker-phabricator/issues/77#issuecomment-624289721

**Comment by juan131** [comment]
Hi @tinder-maxwellelliott 

Thanks for reaching us. Could you please provide a little more context to reproduce the issue?

- Could you please share the `docker-compose` or equivalent command you're using to deploy Phabricator?
- Are you mounting local volumes to persist your data? If that's the case, could you share how?
- Are you a Windows user?

**Comment by tinder-maxwellelliott** [comment]
Here is that docker-compose file https://gist.github.com/tinder-maxwellelliott/e97167acee4fa05bda655109ba0625d5

We are mounting local volumes

No we are using MacOSX for the Docker host

**Comment by juan131** [comment]
Hi @tinder-maxwellelliott  

I think your `docker-compose.yaml` is not defining the volumes properly. Shouldn't you apply the changes below?

```diff
 version: '2'
 services:
   ...
   phabricator:
     ...
     volumes:
-      - 'bitnami/phabricator:latest'
+      - 'phabricator_data:/bitnami'
...
```

**Comment by tinder-maxwellelliott** [comment]
I have updated the gist to match exactly what we are using locally https://gist.github.com/tinder-maxwellelliott/e97167acee4fa05bda655109ba0625d5

**Comment by juan131** [comment]
Hi @tinder-maxwellelliott 

Please note the `MYSQL_ROOT_PASSWORD` environment variable is not needed (it gets ignored by MariaDB container): 

```diff
    environment:
-     - MYSQL_ROOT_PASSWORD=maria_root_password
      - MARIADB_ROOT_PASSWORD=maria_root_password
```

Could you share the output of running the commands below?

```bash
docker-compose exec phabricator ls -la /bitnami/phabricator/data
```

**Comment by marcosbc** [comment]
In https://github.com/bitnami/bitnami-docker-phabricator/issues/77 I mentioned that we have created an internal task for making sure the Phabricator services and the Phabricator UI webapp both run as the same daemon user, to avoid permission issues like the ones mentioned here.
