### ISSUE TITLE
At what URL can the Phabricator be accessed?

### ISSUE THREAD

**Issue by roots-ai** [bitnami/bitnami-docker-phabricator#72]
I've setup the Docker with following commands
```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-phabricator/master/docker-compose.yml
docker-compose up
```

and then started the containers using
`docker-compose start`

Everything seems to work fine, but the Port 80 gives the following error

> Site Not Found
> This request asked for "/" on host, but no site is configured which can serve this request.
> 

Port 443 gives the following error

> Bad Request
> 
> Your browser sent a request that this server could not understand.
> Reason: You're speaking plain HTTP to an SSL-enabled server port.
> Instead use the HTTPS scheme to access this URL, please.
> 
Is it not possible to access this without an HTTPS?

Please help out.

**Comment by juan131** [comment]
Hello @roots-ai 

I just downloaded the latest version of the `docker-compose.yaml` file as you did:

```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-phabricator/master/docker-compose.yml
docker-compose up
```

After that, without running docker-compose start (`docker-compose up` already starts the containers) I opened a browser and access to Phabricator through:

http://127.0.0.1/

or 

https://127.0.0.1/

> Port 443 gives the following error

It's mandatory to use "https" when accessing through port 443.
