### ISSUE TITLE
README.md docker-compse information incorrect

### ISSUE THREAD

**Issue by Elsvent** [bitnami/bitnami-docker-phabricator#79]
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-prestashop/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d

This will install prestashop instead of phabricator

Also environment PHABRICATOR_HOST properties is needed for use.

**Comment by sameersbn** [comment]
thanks for the fix :)
