### ISSUE TITLE
Migrate existing installation

### ISSUE THREAD

**Issue by JoyceBabu** [bitnami/bitnami-docker-phabricator#81]
I am trying to migrate an existing Phabricator installation from [yesnault/phabricator](https://github.com/yesnault/docker-phabricator) image. The yesnault/phabricator image was using `phabricator_` namespace for database names. But `bitnami/phabricator` is using `bitnami_` namespace.

How can I make the container skip the database creation and use the existing database?

**Comment by dbarranco** [comment]
Hi @JoyceBabu 

The Phabricator nami module will skip the creation of the database if there is an installation of the container was made previously and the nami module find some persisted data.

In order to perform a migration of another Phabricator installation I would recommend you to run the Phabricator container and once you have it running, change the configuration file (stored in `/opt/bitnami/phabricator/conf/local/local.json`) and change the database namespace from the `bitnami_phabricator` to the `phabricator_` one.

After that, restoring your database and restarting the container would make the Phabricator nami module to use the new namespace.

Best regarrds!

**Comment by ethicalmohit** [comment]
Is it solved?

**Comment by ethicalmohit** [comment]
> Hi @JoyceBabu
> 
> The Phabricator nami module will skip the creation of the database if there is an installation of the container was made previously and the nami module find some persisted data.
> 
> In order to perform a migration of another Phabricator installation I would recommend you to run the Phabricator container and once you have it running, change the configuration file (stored in `/opt/bitnami/phabricator/conf/local/local.json`) and change the database namespace from the `bitnami_phabricator` to the `phabricator_` one.
> 
> After that, restoring your database and restarting the container would make the Phabricator nami module to use the new namespace.
> 
> Best regarrds!

I thought of this method only but when i tried to login into my container, it keeps on exiting with below error even before i do something.

```
Error executing 'postInstallation': MySQL command failed to run. Error: 
Mar 10 23:38:31 ip-10-0-224-132.ec2.internal phabricator:   ERROR 1044 (42000) at line 1: Access denied for user 'phab_user'@'%' to database 'bitnami_phabricator_VNZAi'
```

**Comment by ethicalmohit** [comment]
> Hi @JoyceBabu
> 
> The Phabricator nami module will skip the creation of the database if there is an installation of the container was made previously and the nami module find some persisted data.
> 
> In order to perform a migration of another Phabricator installation I would recommend you to run the Phabricator container and once you have it running, change the configuration file (stored in `/opt/bitnami/phabricator/conf/local/local.json`) and change the database namespace from the `bitnami_phabricator` to the `phabricator_` one.
> 
> After that, restoring your database and restarting the container would make the Phabricator nami module to use the new namespace.
> 
> Best regarrds!

Also, In your case what will happen when container restarts. We are not storing any persistence data on the machine. Everything is stored inside the container of aws ecs cluster.

**Comment by JoyceBabu** [comment]
I ended up choosing a different docker image. I had already migrated to the new image, when @dbarranco suggested the work around. I planned to try it some day, but never got around to it.

**Comment by marcosbc** [comment]
Hi, in https://github.com/bitnami/bitnami-docker-phabricator/issues/117 we suggested a possible workaround for this.

Note that you may also need to change `storage.default-namespace` in the config if the prefix is different.
