### ISSUE TITLE
Will not start after install

### ISSUE THREAD

**Issue by benisameme** [bitnami/bitnami-docker-phabricator#83]
**Description**

When I run `docker-compose up -d` it shows the installer on the webpage and then it just stops the container and when you try to start it again it just stops about 15 seconds after.

**Steps to reproduce the issue:**
- Run `docker-compose up -d`

**Describe the results you received:**
When I run it I get `root@REEEEE:~# docker-compose up -d
root_mariadb_1 is up-to-date
root_phabricator_1 is up-to-date
`

**Describe the results you expected:**
A fully working phabriactor instance

**Additional information you deem important (e.g. issue happens only occasionally):**
no

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.3MiB
Name: REEEEE
ID: G4Z7:J45A:VGNE:ODGM:XMK6:CVL2:PD7P:5KY3:I2UO:JWJF:KNHT:ZYRX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I'm using a Ubuntu VM hosted on Digitalocean

**Comment by dbarranco** [comment]
Hi @benisameme 

I am sorry for the delay on my answer.
Could you please execute these commands in order to clean the environment and launch again the container?
Checking it manually and from our daily builds of the Phabricator container I am unable to reproduce this issue.

```
docker-compose down -v && docker-compose pull && docker-compose up --build --force-recreate
```

> Warning: note that this command will delete all the volumes you before created of phabricator. Please, move to another location in order to save them.

Best regards!
