### ISSUE TITLE
phabricater launching issue

### ISSUE THREAD

**Issue by madhukararelly** [bitnami/bitnami-docker-phabricator#85]
launch the phabricator  using docker-compose file. but when you launching the application issue coming like:

Site Not Found
This request asked for "/" on host "192.168.20.125", but no site is configured which can serve this request.

**Comment by akaustel** [comment]
Same problem here. Did you figure something out?

**Comment by akaustel** [comment]
You must set the `PHABRICATOR_HOST` to match the host name you use in the browser. Access via http://127.0.0.1 is the default. Not `localhost` but `127.0.0.1`.

**Comment by juan131** [comment]
Yes! As @akaustel mentioned the default value is `127.0.0.1`. You can check the default values in the Environment Variables section of the README:
https://github.com/bitnami/bitnami-docker-phabricator#environment-variables

@madhukararelly are you able to connect to Phabricator setting the hostname with the `PHABRICATOR_HOST` env var?

**Comment by uhbif19** [comment]
@juan131 Access through `localhost` does not work. I think this is not intuitive, and better be mentioned in README.

**Comment by juan131** [comment]
Hi @uhbif19 

Do you mean by adding a warning or sth like that? Please feel free to do a PR with you suggestion to improve the README.md file.
