### ISSUE TITLE
How do you configure locked options with this image?

### ISSUE THREAD

**Issue by subyraman** [bitnami/bitnami-docker-phabricator#86]
The Phab guide has some guidance about configuring locked options. Specifically, I'd like to configure `feed.http-hooks`: https://secure.phabricator.com/book/phabricator/article/configuration_locked/

I ran `docker exec -it phabinstance_phabricator_1 bash` but can't figure out how to get to the config to set this option. Is it located somewhere I haven't found?

**Comment by RajatNair** [comment]
You can get http-hooks config values using -
`/opt/bitnami/phabricator/bin/config get feed.http-hooks`

You can set http-hooks config values using -
`/opt/bitnami/phabricator/bin/config set feed.http-hooks <value>`

**Comment by juan131** [comment]
Thanks for sharing the solution @RajatNair ! They worked for me! I proceed to close this issue. Please feel free to open it again if you need further assistance or the commands don't work as you expect @subyraman
