### ISSUE TITLE
Support Git cloning over SSH

### ISSUE THREAD

**Issue by altendky** [bitnami/bitnami-docker-phabricator#99]
Already discussed over in #55 including https://github.com/bitnami/bitnami-docker-phabricator/issues/55#issuecomment-285640738.

I have made a horrible 'script' that results in me being able to clone via SSH.

Note that pasting the below in three batches works better at least via the Portainer console.  Otherwise it seems to like to lose some of the input.

```bash
apt update

apt install -y openssh-server

cd /opt/bitnami/phabricator
bin/config set diffusion.ssh-port 22
bin/config set diffusion.ssh-user git
sed -e 's;/path/to/phabricator;/opt/bitnami/phabricator;' -e 's/vcs-user/git/' resources/sshd/phabricator-ssh-hook.sh > /opt/phabricator-ssh-hook.sh
chmod 755 /opt/phabricator-ssh-hook.sh
sed -e 's/2222/22/' -e 's/vcs-user/git/' -e 's;/usr/libexec/;/opt/;' resources/sshd/sshd_config.phabricator.example > /etc/ssh/sshd_config.phabricator
echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config.phabricator
sed -i 's;^\(git:.*\):/home/phabricator:;\1:/opt/bitnami/phabricator:;' /etc/passwd
sed -i 's/git:!:/git:*:/' /etc/shadow
sed -i 's;SSHD_OPTS=.*;SSHD_OPTS="-f /etc/ssh/sshd_config.phabricator";' /etc/default/ssh
sed -i 's;\(\$root = \)dirname;\1;' /opt/bitnami/phabricator/bin/ssh-auth
mkdir -p ~git/.ssh
echo 'PATH=/usr/bin:/opt/bitnami/php/bin' >> ~git/.ssh/environment
chown git:git ~git/.ssh/environment
update-rc.d ssh enable
service ssh start
```

Aside from this not being how you build a container...  I suspect there are some bad security choices as well.  And at least the username should probably be env-var configurable.  Etc.

Mostly at this point I'm curious about @dbarranco's comment that the ssh stuff should be in a separate composed container.  The ssh serving uses the phabricator php scripts so it's not obvious to me that it should be in a separate container (says the guy who started running docker last month).  The point made about persisting the ssh config (fingerprint anyways, not sure offhand what else) makes sense.

Big picture, I"m trying to build up a copy of Phabricator with build server integration, presently trying with a composed Jenkins container.

**Comment by altendky** [comment]
Maybe I should be using `bitnami-pkg` but I haven't found a way to search for existing packages yet.

**Comment by juan131** [comment]
Hi @altendky 

> Mostly at this point I'm curious about @dbarranco's comment that the ssh stuff should be in a separate composed container. The ssh serving uses the phabricator php scripts so it's not obvious to me that it should be in a separate container (says the guy who started running docker last month).

The idea is to have two different containers. One running Gitolite or any other Git hosting server, and another container running Phabricator. You'll need to open the ports to allow the communication between Phabricator and the Git server. 

This way, you respect the principle "one process, one container" on your design and isolate your solutions. This is essential to identify possible issues with RAM, space, etc. 

> Maybe I should be using bitnami-pkg but I haven't found a way to search for existing packages yet.

What do you want to use **bitnami-pkg** for? Please note that tool only downloads and install the required Nami modules for a specific solution.

**Comment by altendky** [comment]
Thanks for the follow up @juan131.

Phabricator does its own Git serving with permissions configured in Phabricator etc.  The Bitnami Phabricator image already does this over https, but not ssh.  I can't say I'm familiar with Gitolite beyond it's name but it doesn't sound like it's a proper alternative if we want to use the Phabricator Git serving features over ssh.  I get that not everyone would want to use the Phabricator Git SSH server so any implementation of what I'm doing might only be optional or not even get accepted to `bitnami-docker-phabricator`, but it does seem a valid option.  Unless you think having another container for SSH that talks across to the Phabricator container is what I should be looking at?

I was having some issues with bringing up a new Phabricator image that made me wonder if my use of `apt-get` or some of my other hackery was causing the issue.  That's when I was wondering if I should be using `bitnami-pkg` or such instead of `apt-get`.  Turns out I had a volume path wrong in the compose file.  Is use of `apt-get` like I have reasonable for dependencies in a Bitnami-derivative image or is it likely to cause issues?

It's still a mess but at least I've got all my custom stuff into the `docker-compose.yml` and a couple `Dockerfile`s.

https://github.com/altendky/docker-compose-phabricator-jenkins/tree/5630d63b5d66d44f8c3d0023bb5ca92a95ca0907

**Comment by juan131** [comment]
Hi @altendky 

> I get that not everyone would want to use the Phabricator Git SSH server so any implementation of what I'm doing might only be optional or not even get accepted to bitnami-docker-phabricator, but it does seem a valid option.

I agree with you. Phabricator should be configurable with Git SSH and this docker image should support both configurations even if this one is included as an "optional" solution.

> I can't say I'm familiar with Gitolite beyond it's name but it doesn't sound like it's a proper alternative if we want to use the Phabricator Git serving features over ssh

The suggestion of using Gitolite is just to avoid overloading the Phabricator container. Please note that when using containers we should isolate the solutions as much as possible even if they're closely related. 

E.g. I need more RAM because Git is consuming too much. On a scenario where you have Git and Phabricator on different containers you could scale the Git container maintaining Phabricator as it is.

> I was having some issues with bringing up a new Phabricator image that made me wonder if my use of apt-get or some of my other hackery was causing the issue. That's when I was wondering if I should be using bitnami-pkg or such instead of apt-get

We include a tool called **install_packages** on the base image used by Phabricator (Minideb). You can install any package you may required by running:

```
install_packages XXX
```

> Is use of apt-get like I have reasonable for dependencies in a Bitnami-derivative image or is it likely to cause issues?

It depends. 

Bitnami Phabricator image includes some components (such as: PHP, MySQL client, Git, Phabricator or Apache) which have been installed using "Nami based" utilities. For instance, if you want to install a PHP extension, you'd have to take into account this and you'll need to adapt the installation process to it.

However, you can use **apt** to install other components on the system (e.g. OpenSSL)

> It's still a mess but at least I've got all my custom stuff into the docker-compose.yml and a couple Dockerfiles.

Regarding your [Dockerfile](https://github.com/altendky/docker-compose-phabricator-jenkins/blob/5630d63b5d66d44f8c3d0023bb5ca92a95ca0907/phabricator/Dockerfile), there are a serie of actions such as:

```
RUN bin/config set diffusion.ssh-port 22
RUN bin/config set diffusion.ssh-user git
RUN sed -e 's;/path/to/phabricator;/opt/bitnami/phabricator;' -e 's/vcs-user/git/' resources/sshd/phabricator-ssh-hook.sh > /opt/phabricator-ssh-hook.sh
RUN chmod 755 /opt/phabricator-ssh-hook.sh
RUN sed -e 's/2222/22/' -e 's/vcs-user/git/' -e 's;/usr/libexec/;/opt/;' resources/sshd/sshd_config.phabricator.example > /etc/ssh/sshd_config.phabricator
RUN echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config.phabricator
RUN sed -i 's/git:!:/git:*:/' /etc/shadow
RUN sed -i 's;SSHD_OPTS=.*;SSHD_OPTS="-f /etc/ssh/sshd_config.phabricator";' /etc/default/ssh
RUN sed -i 's;\(\$root = \)dirname;\1;' /opt/bitnami/phabricator/bin/ssh-auth
RUN mkdir -p /home/phabricator/.ssh
RUN echo 'PATH=/usr/bin:/opt/bitnami/php/bin' >> /home/phabricator/.ssh/environment

RUN sed -i 's;\(exec .*\);usermod --password \\* git\nusermod --unlock git\nchown git:git ~git/.ssh/environment\nservice ssh start\n\1;' /app-entrypoint.sh
```

That consists on changing the configuration or modifying the **app-entrypoint.sh**. I would move all this actions to the **app-entrypoint.sh** itself and modify it directly. See our [Dockerfile](https://github.com/bitnami/bitnami-docker-phabricator/blob/master/2018/Dockerfile) and how it adds the directory from the "roots" directory:

```
...
COPY rootfs /
...
```

**Comment by altendky** [comment]
Thanks again for the detailed reply.

If I weren't wanting to use the Phabricator Git server a separate container would make perfect sense.  For using Phabricator's features for Git, there may be a sensible way to separate sshd into a separate container, I haven't looked but Phabricator would still be the actual Git server as far as I know.  That said, Phabricator does offer [clustering](https://secure.phabricator.com/book/phabricator/article/cluster_repositories/).  Though, "Repository hosts must run a complete, fully configured copy of Phabricator, including a webserver. They must also run a properly configured sshd."  So, we still end up with Phabricator coexisting with a webserver and sshd, even if we run multiple containers to spread the load.

I just switched over to `install_packages`, thanks.  https://github.com/altendky/docker-compose-phabricator-jenkins/commit/800e456b00c5ededecefe968cbbbf9b7225c380b  The comments about Nami for PHP extensions on the Phabricator image and similar scenarios makes sense.

That block of `sed`s you mention does look to be a mess.  I was definitely hacking it.  That said, it would be nice to have a simple way to add stuff to the `app-entrypoint.sh` that doesn't involve manually copying it from the base image and keeping the copy up to date.  I'd imagine a line in there that runs another file if it exists.  Then we can just append our own script to:

`app-entrypoints-extras.sh`
```sh
source myspecialscript.sh
```

and add our own stuff into that other file:

`myspecialscript.sh`
```sh
PATH=/usr/bin/:/opt/bitnami/php/bin
```

No fiddling with a pre-docker-build step to insert the data into the parent image's file.

But, this may also come back to my asking about the `bitnami-pkg` package format.  I'm guessing it has something to do with generating the `apache php phabricator` list in here?

```sh
if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
  nami_initialize apache php phabricator
  info "Starting phabricator... "
fi
```

If so, then making my own `bitnami-pkg` for sshd would start to deal with my mess of insertions directly into `app-entrypoint.sh`.

**Comment by juan131** [comment]
> But, this may also come back to my asking about the bitnami-pkg package format. I'm guessing it has something to do with generating the apache php phabricator list in here?

Yes, **bitnami-pkg** downloads the Nami modules from our repositories and then they are initialised on the **app-entrypoint.sh** as you pointed.

> If so, then making my own bitnami-pkg for sshd would start to deal with my mess of insertions directly into app-entrypoint.sh.

**bitnami-pkg** doesn't support custom modules at this moment. Therefore, you can't use it to create your own solution of **sshd**. I've created an internal task to implement a module for **sshd** so we can support it on this Docker Image. 

> That block of seds you mention does look to be a mess. I was definitely hacking it. That said, it would be nice to have a simple way to add stuff to the app-entrypoint.sh that doesn't involve manually copying it from the base image and keeping the copy up to date. I'd imagine a line in there that runs another file if it exists.

We implemented sth similar on other images. For instance, see [Matomo](https://github.com/bitnami/bitnami-docker-matomo/tree/master/3/rootfs). As you can check, the `app-entrypoint.sh` includes other config from `init.sh`:

```
if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  . /init.sh
  nami_initialize apache php mysql-client matomo
  info "Starting matomo... "
fi
```

Therefore, we can use the `init.sh` to add custom configuration.

**Comment by lindblandro** [comment]
I'm migrating our old server installation on top of docker and using version `2016.40-r0`, which is pretty old I know, and I'm planning on upgrading once the migrain... migration is over, but this seems to affect `2018.41` as well. I noticed that phabricator's data directory `/bitnami/phabricator` is chown'd to `webserverHandler.user` and `webserverHandler.group` (i.e. `daemon:daemon`) every time a container is created. So I'm having:
```
$ ls -l /bitnami/phabricator/repo
drwxr-xr-x 7 daemon daemon 4096 Oct 15 13:12 AREPO
$ 
 ```
instead of 
```
$ ls -l /bitnami/phabricator/repo
drwxr-xr-x 7 phabricator phabricator 4096 Oct 15 13:12 AREPO
$ 
```
I've modified `Dockerfile` to create a `git` user for authenticating via ssh. Phabricator apparently tries to run git commands inside the repositories using something like `git@phabricator$ sudo -En -u phabricator git-receive-pack /path/to/repo` which fails since `phabricator` user doesn't have write privileges to the repo. Doing a `chown -R phabricator:phabricator /bitnami/phabricator` solves the issue. The problem with this is that it has to be done every time the container is recreated and since there isn't any real slot to drop custom initialization code (AFAIK) this becomes unnecessarily messy.

Is there a way to configure bitnami's phabricator package (the one installed using `bitnami-pkg`) so that the owner / mode of directories under `/bitnami/phabricator` is set to something specific instead of `daemon:daemon / 0755`? 

In my old installation I had `data` set as `phabricator:www-data / 0750` and `repo` `phabricator:www-data / 0755` (`www-data` corresponds to `daemon`) so just changing the default owner of those files would be sufficient.

Also, does bitnami have some sort of public index or repository of packages available through `bitnami-pkg`?

**Comment by lindblandro** [comment]
>  I was unable to reproduce it using the latest version of Phabricator:
Ok, that's excellent. Which version is this exactly?

**Comment by juan131** [comment]
Hi @lindblandro 

I'm using the **latest** tag:

```
$ docker pull bitnami/redmine:latest
$ docker-compose up -d 
$ docker-compose exec phabricator ls -la /bitnami/phabricator
...
```

**Comment by altendky** [comment]
`redmine`?

**Comment by juan131** [comment]
Ops! You're right @altendky

Sorry for the mistake!

````
$ docker pull bitnami/phabricator:latest
$ docker-compose up -d 
$ docker-compose exec phabricator ls -la /bitnami/phabricator
...
```

**Comment by altendky** [comment]
@stale, I don't believe this has been resolved.

**Comment by juan131** [comment]
You're right @altendky 

The original issue hasn't been resolved and, indeed, there's a opened task in our backlog to work on that in the future.

**Comment by cooperspencer** [comment]
Is there any progress?

**Comment by juan131** [comment]
I'm afraid we didn't have the chance to work on this feature yet.

I'll try to give it more priority so we can work on fixing this sooner. Thanks so much for your consideration and patience.

**Comment by cooperspencer** [comment]
@juan131 thanks for the effort and the quick response. Really looking forward to it.

**Comment by cooperspencer** [comment]
@juan131 I created a merge request for this issue. I played a bit around and was able to add the ability to create a custom ssh port config.

**Comment by juan131** [comment]
Hi @cooperspencer 

Thanks so much for your contribution!!! Let me take a look and I'll come back to you with feedback about what you did! We really appreciate users like you who take a step forward and contribute to the docker image!

**Comment by cooperspencer** [comment]
@juan131 you are welcome. I really hope that it helps somehow.

**Comment by altendky** [comment]
@cooperspencer do you have a summary of what you did significantly differently than I had above?  Also, I was under the impression that the proper solution involved Bitnami-internal work to create an `sshd` package etc, I suppose with proper configurability so we don't have to sed-it stuff.  https://github.com/bitnami/bitnami-docker-phabricator/issues/99#issuecomment-395041687

**Comment by cooperspencer** [comment]
There is basically not much difference between your script and what I did. But with my changes, the need for a special script is gone. And you can use a custom port, so I haven't hardcoded port 22 in my config.

**Comment by altendky** [comment]
@cooperspencer alrighty.  Thanks for the explanation and for sharing the work.  Hopefully this can end up properly integrated and easily available to all.  :]

**Comment by juan131** [comment]
Hi @altendky @cooperspencer 

>  was under the impression that the proper solution involved Bitnami-internal work to create an sshd package

We don't have any package for `sshd`, for instance take a look to the [Bitnami Docker Git Dockerfile](https://github.com/bitnami/bitnami-docker-git/blob/master/2/debian-9/Dockerfile) and you'll find we're adding the `ssh` system package:

```Dockerfile
...
RUN install_packages libc6 libcomerr2 libcurl3 libffi6 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libhogweed4 libidn11 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libnettle6 libnghttp2-14 libp11-kit0 libpsl5 librtmp1 libsasl2-2 libssh2-1 libssl1.0.2 libssl1.1 libtasn1-6 libunistring0 ssh zlib1g
...
```

> I suppose with proper configurability so we don't have to sed-it stuff

Ideally we'll move all this logic to the Phabricator Nami modules so all the Phabricator's initialization logic is bundled in the same module.

**Comment by acmcarther** [comment]
(My understanding is that this bug is tied to the fix in https://github.com/bitnami/bitnami-docker-phabricator/pull/125#issuecomment-520479271)

Hi @juan131. 

I tried to use the `PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY` setting in a new Phabricator installation (specifically `docker.io/bitnami/phabricator:2019.34.0`), and it looks like there might be a bug in the substitution of `/etc/ssh/sshd_config` that causes sshd to fail to start.

First, the error in my container logs.
```
INFO  ==> Starting phabricator...                                                              
Starting SSH...
AuthorizedKeysCommand set without AuthorizedKeysCommandUser                                    
Starting OpenBSD Secure Shell server: sshd failed!                                             
Starting Apache...
```

I see these initial lines in my running container's `/etc/ssh/sshd_config`:
```
AuthorizedKeysCommand /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh
AuthorizedKeysCommand /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh
AllowUsers git
```

Based on the [Phabricator-provided template](https://github.com/phacility/phabricator/blob/master/resources/sshd/sshd_config.phabricator.example#L6-L8) that this file is derived from, the second "AuthorizedKeysCommand" should actually be "AuthorizedKeysCommandUser", probably with value "git".

It looks to me like the nami phabricator script is trying to do this, but might be performing the substitutions in an unfortunate order such that the first pattern replaces the line the second pattern should replace. I see the following in my running container's `/root/.nami/components/com.bitnami.phabricator/helpers.js`:

```js
$app.helpers.configureGitRepository = function(webserverHandler) {
  // unrelated lines omitted  
  if ($app.enableGitSSHRepository === 'yes') {
    // unrelated lines omitted
    $file.substitute('/etc/ssh/sshd_config', [{
      pattern: new RegExp(`^\s*AuthorizedKeysCommand\s*.*$`, 'm'),
      value: `AuthorizedKeysCommand ${$file.join($app.installdir, 'resources', 'sshd', 'phabricator-ssh-hook.sh')}`,
    }, {
      pattern: new RegExp(`^\s*AuthorizedKeysCommandUser\s*.*$`, 'm'),
      value: `AuthorizedKeysCommandUser ${$app.systemVCSUser}`,
    }, /* more unrelated lines omitted */], {});
    // unrelated lines omitted
  }
}
```
I couldn't find the source for this bitnami package in order to patch this for myself locally and/or send a pull request, but the fix should be as simple as appending a space after the command in the regex pattern, or swapping the order of the substitutions.

**Comment by juan131** [comment]
Hi @acmcarther 

Sorry for the late response. You're totally right and there's a bug in the `helpers.js` script. I just fixed it and released a new revision (**2019.35.0-r6**) of the Phabricator image including the fix.

Here are the changes I applied:

```
@@ -132,16 +132,16 @@ $app.helpers.configureGitRepository = function(webserverHandler) {
       '/etc/ssh/sshd_config'
     );
     $file.substitute('/etc/ssh/sshd_config', [{
-      pattern: new RegExp(`^\s*AuthorizedKeysCommand\s*.*$`, 'm'),
+      pattern: new RegExp(`^\s*AuthorizedKeysCommand\s+.*$`, 'm'),
       value: `AuthorizedKeysCommand ${$file.join($app.installdir, 'resources', 'sshd', 'phabricator-ssh-hook.sh')}`,
     }, {
-      pattern: new RegExp(`^\s*AuthorizedKeysCommandUser\s*.*$`, 'm'),
+      pattern: new RegExp(`^\s*AuthorizedKeysCommandUser\s+.*$`, 'm'),
       value: `AuthorizedKeysCommandUser ${$app.systemVCSUser}`,
     }, {
-      pattern: new RegExp(`^\s*AllowUsers\s*.*$`, 'm'),
+      pattern: new RegExp(`^\s*AllowUsers\s+.*$`, 'm'),
       value: `AllowUsers ${$app.systemVCSUser}`,
     }, {
-      pattern: new RegExp(`^\s*Port\s*.*$`, 'm'),
+      pattern: new RegExp(`^\s*Port\s+.*$`, 'm'),
       value: `Port ${$app.sshServerPort}`,
     }], {abortOnUnmatch: true});
   }
```

**Comment by acmcarther** [comment]
@juan131
Thanks for the quick turnaround on this issue. I gave the latest version a shot (2019.35.0-r6) and it looks like there might be another bug. My logs (trace level 8)
```
phabric TRACE [substitute] File normalization: /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh -> /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh              
phabric TRACE [chmod] File normalization: /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh -> /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh                   
phabric TRACE [copy] File normalization: /opt/bitnami/phabricator/resources/sshd/sshd_config.phabricator.example -> /opt/bitnami/phabricator/resources/sshd/sshd_config.phabricator.example    
phabric TRACE [substitute] File normalization: /etc/ssh/sshd_config -> /etc/ssh/sshd_config                                                                                                    
Error executing 'postInstallation': File /etc/ssh/sshd_config did not match any of the provided substitutions                                                                                  
nami    TRACE Error: Error executing 'postInstallation': File /etc/ssh/sshd_config did not match any of the provided substitutions                                                             
    at /opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:47:13                                                                                                                  
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)                                                                                                                                
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)                                                                                                                     
    at _massFileSubstitute (/opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:39:5)                                                                                             
    at Object.substitute (/opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:180:5)                                                                                              
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)                                                                                            
    at Object.$app.helpers.configureGitRepository (/root/.nami/components/com.bitnami.phabricator/helpers.js:134:11)                                                                           
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.phabricator/main.js:137:16)                                                                                           
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)                                                                                           
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)                                                                                               
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)                                                                                                                                
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)                                                                                                                     
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)                                                                                                                                                                                                                                                                                           
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)                                                                                              
    at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)                                                                                                                     
    at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:524:30)
```

I tried this image with a fresh DB and Phabricator data directory and ended up with the same result. I'm not sure how to interpret "did not match any of the provided substitutions", that may mean that the file was missing or that one or more patterns were not matched.

**Comment by austinsk8s** [comment]
This seems to work with bitnami/phabricator:2020 to an extent, but I'm having an issue...

I am on my local machine, ssh'd into my host that has bitnami running in a container, but not exec'd into the container.

`echo {} | ssh git@myRemoteHostThatIamCurrentlySSHdInto -p 2222`

> phabricator-ssh-exec: Welcome to Phabricator.
> You are logged in as alincoln.

But if I try from my local machine:

`echo {} | ssh git@sameHostAsBeforeButAccessedFromMyLocalMachine -p 2222`

> Pseudo-terminal will not be allocated because stdin is not a terminal.
> ssh: connect to host  port 2222: Operation timed out

I chalked it up to a firewall issue, but it seems like that is set up correctly... Maybe some sort of port forwarding isn't working? Anyone here have experience with an issue like this?

**Comment by juan131** [comment]
Hi @austinsk8s 

I guess you need to create a SSH tunnel if you want to access your container via SSH. The container host you're trying to access is not exposed by the remote server. Therefore, you can't access it from the local machine unless you crate a tunnel

- Step 1. Create a SSH Tunnel from "Local Machine" to "Remote Server"
- Step 2. While the tunnel is up, access the container via SSH

In the link below you can find information about how to create a SSH tunnel:

- https://docs.bitnami.com/general/faq/get-started/access-ssh-tunnel/
